### ISSUE TITLE
Nades not being saved

### ISSUE THREAD

**Issue by olliee** [splewis/csgo-practice-mode#10]
### Expected behavior
Nades should be saved in the file for future use.

### Actual behavior
Nades are not saved at all, no file is made but nades work while the map is loaded. Nades will no longer be saved when you change the map.

### Steps to reproduce
- Plugin version: 1.1.0
- Sourcemod version: 1.8

### Extra info
I believe that I have given ownership to the user (csgo_wolfpack) of the folder in /home/csgo_wolfpack (location of server), as this is ran on linux.

**Comment by splewis** [comment]
Check error logs (adding/sourcemod/logs) and double check the write permissions.

**Comment by splewis** [comment]
Closed due to no response.
