### ISSUE TITLE
Practice Config

### ISSUE THREAD

**Issue by SuplenC** [splewis/csgo-practice-mode#104]
### Request
1) Config execute on load - So I have installed both pugsetup and practicemode, I've changed both warmup and live configs, and when warmup is running there are no grenades on (on pug), but after setting practicemode, warmup is being executed and again, on practicemode there are no grenades. So I would request an option to execute practice config while loading practice mode that would be separate one if available if possible.

**Comment by splewis** [comment]
I moved your request for a command to exit the dry run mode to a separate issue.  

I'm not sure exactly what you're requesting here. It sounds like you can just put whatever cvars in your [practicemode.cfg](https://github.com/splewis/csgo-practice-mode/blob/master/configs/practicemode.cfg#L32) file?

**Comment by SuplenC** [comment]
Yes that worked out. I put the alias recall that execs the config as the last cvar and it work perfectly. Closing it then.
