### ISSUE TITLE
Practice mode not working after dangerzone update

### ISSUE THREAD

**Issue by Bork1337** [splewis/csgo-practice-mode#106]
Hello 

I have used sourcemod with the plugin "csgo-practice-mode" for more than 2 years now, and yesterday when i went into my server all of the sudden i could not join a team and got auto-disconnected from the server after 30 seconds due to lost connection.

I then tried to update the sourcemod which didn't help, after that i tried to update the csgo-practice-mode plugin and still i could not join any team. 

Then i tried to remove both sourcemod and csgo-practice-mode which then allowed me to join a team on my server. Then i installed sourcemod and it worked as it should with the command !admin and i tested in the consol with the command "meta list" and sourcemod is running

I then downloaded the newest version of csgo-practice-mode (which is version 1.3.3 added 04-08-2018) and when i installed this plugin same problem as before, i can't join a team when i connect to the server. 

Any help would be very appreciated as it is pretty annoying not being able to use our server to practice xD

**Comment by invadeofficial** [comment]
I have a problem like that too, my server keeps crashing everytime im trying to either place a bot or make a replay. Basically everytime a bot is included the server crashes. This only happens when practicemode is enabled :((

**Comment by splewis** [comment]
I just confirmed everything works as expected on my development server. Can you post the output of running these in console:

```
sm version
sm exts
sm plugins
```

**Comment by invadeofficial** [comment]
Mine says - 
- sm version
SourceMod 1.9.0.6260, by AlliedModders LLC
To see running plugins, type "sm plugins"
To see credits, type "sm credits"
Visit http://www.sourcemod.net/

- sm exts
 "Automatic Updater" (1.9.0.6260) by AlliedModders LLC: Updates SourceMod gamedata files
 "Webternet" (1.9.0.6260) by AlliedModders LLC: Extension for interacting with URLs
 "CS Tools" (1.9.0.6260) by AlliedModders LLC: CS extended functionality
 "BinTools" (1.9.0.6260) by AlliedModders LLC: Low-level C/C++ Calling API
 "SDK Tools" (1.9.0.6260) by AlliedModders LLC: Source SDK Tools
 "Client Preferences" (1.9.0.6260) by AlliedModders: Saves client preference settings
 "SQLite" (1.9.0.6260) by AlliedModders LLC: SQLite Driver
 "Top Menus" (1.9.0.6260) by AlliedModders: Creates sorted nested menus
 "SDK Hooks" (1.9.0.6260) by AlliedModders LLC: Source SDK Hooks

- sm plugins
 "Basic Chat" (1.9.0.6260) by AlliedModders LLC
 "Admin Help" (1.9.0.6260) by AlliedModders LLC
 "Client Preferences" (1.9.0.6260) by AlliedModders LLC
 "Fun Votes" (1.9.0.6260) by AlliedModders LLC
 "Basic Info Triggers" (1.9.0.6260) by AlliedModders LLC
 "CS:GO Pause Commands" (1.0.0) by splewis
 "Basic Ban Commands" (1.9.0.6260) by AlliedModders LLC
 "Bot Mimic" (2.1) by Jannik "Peace-Maker" Hartung
 "Anti-Flood" (1.9.0.6260) by AlliedModders LLC
 "Basic Commands" (1.9.0.6260) by AlliedModders LLC
 "Basic Votes" (1.9.0.6260) by AlliedModders LLC
 "Basic Comm Control" (1.9.0.6260) by AlliedModders LLC
 "Nextmap" (1.9.0.6260) by AlliedModders LLC
 "Admin File Reader" (1.9.0.6260) by AlliedModders LLC
 "csutils" (1.3.3) by splewis/Deathknife
 "CS:GO PracticeMode" (1.3.3) by splewis
 "Player Commands" (1.9.0.6260) by AlliedModders LLC
 "Fun Commands" (1.9.0.6260) by AlliedModders LLC
 "Admin Menu" (1.9.0.6260) by AlliedModders LLC
 "Reserved Slots" (1.9.0.6260) by AlliedModders LLC
 "Sound Commands" (1.9.0.6260) by AlliedModders LLC

**Comment by Bork1337** [comment]
Hi i found the problem.

i had to install a new metamod bin for it to work, dont know why xD

thanks for the help :D!
