### ISSUE TITLE
.bot <.tbot & .ctbot> command keep crashes the server

### ISSUE THREAD

**Issue by dame2000** [splewis/csgo-practice-mode#108]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
spawning bots on the team

### Actual behavior
Server stops immediately, and crashes the server.

### Steps to reproduce
- Plugin version: latest github version
- Sourcemod version: latest stable build  
 SourceMod Version Information:
    SourceMod Version: 1.9.0.6260
    SourcePawn Engine: 1.9.0.6260, jit-x86 (build 1.9.0.6260)
    SourcePawn API: v1 = 4, v2 = 12
    Compiled on: Oct 14 2018 05:08:53
    Built from: https://github.com/alliedmodders/sourcemod/commit/48f7e6b
    Build ID: 6260:48f7e6b
    http://www.sourcemod.net/

- Steps to reproduce (please be specific):

I tried remaking the whole server and put practicemode plugin.
and all commands were good except the bot related commands.
if I use the bot command <play, add, team> => it just crash the server immediately.

what's the reason? did I do something wrong at the srcds setting part?

**Comment by splewis** [comment]
> what's the reason?

I can't answer that. All I can suggest is:
- update sourcemod to a more recent 1.9 snapshots
- remove any plugins that may be conflicting (skin/knife plugins, in particular)

**Comment by splewis** [comment]
Closing since there's been no update here.
