### ISSUE TITLE
Extract a bot replay from a demo

### ISSUE THREAD

**Issue by Sornii** [splewis/csgo-practice-mode#113]
Hi,

This can be a major enhancement, I can't event imagine the effort needed to make this reality. I was thinking these days... What if we could provide an csgo demo and extract a bot replay and play it on the server so we can actually see it in the server.

Am I being too exaggerated?

Cya!

**Comment by splewis** [comment]
I originally intended to do this at some point, but it's a pretty difficult task and I think it's extremely unlikely anyone actually gets to it.

**Comment by Sornii** [comment]
Hi @splewis,

What about the help from the ones at CSGO Demo Manager?
https://github.com/akiver/CSGO-Demos-Manager

We could actually make this happen with each one helping the other.

**Comment by splewis** [comment]
Anyone is free to send a pull request. I have no intention of working on this.
