### ISSUE TITLE
Feature Request: Re-Number or Re-ID

### ISSUE THREAD

**Issue by stealthrs** [splewis/csgo-practice-mode#117]
Is it possible we could have a plugin feature so we can re-number or re-id the grenades?

I've added a lot of grenades; but, they're all out of order.  So if I type .find and type a specific nade location and type .next I would like it to go next on the grenade list from the .find menu.  

The only real way to do this is by re-id numbering them.  Well... That's a bit of a chore alone (especially when you have 100+ nades on each map).

What do you think?

**Comment by splewis** [comment]
Highly unlikely to happen.

I have some recommendations on how to keep things organized at https://github.com/splewis/csgo-practice-mode/wiki/Notes-for-power-users#keeping-your-saved-grenades-organized.

**Comment by stealthrs** [comment]
That was helpful, thanks.

When I use the sm_practicemode_alphabetize_nades and sm_practicemode_share_all_nades vars, which .cfg are these settings BEST located in?  Is it csgo\cfg\sourcemod\sourcemod.cfg ?

Thanks.
