### ISSUE TITLE
How many time take to show in the folder my grenades?

### ISSUE THREAD

**Issue by Crymore13** [splewis/csgo-practice-mode#12]
I saved several grenades , I'm hoping it's been 10 minutes and nothing appears in the "csgo\addons\SourceMod\data\practicemode\Grenades"

How many time I will have to wait? There is something I have to do to show there?

**Comment by bykidi** [comment]
a command on force-saving it will be great imo

**Comment by splewis** [comment]
Currently the backing files are only updated on map changes.

**Comment by Crymore13** [comment]
>Currently the backing files are only updated on map changes.

And when the player disconnects from the server... 
Thanks!

**Comment by splewis** [comment]
You're right, it also always saved when **any** user disconnects. 

https://github.com/splewis/csgo-practice-mode/blob/master/scripting/practicemode.sp#L392
