### ISSUE TITLE
Cannot drop weapons

### ISSUE THREAD

**Issue by Erfa** [splewis/csgo-practice-mode#120]
I'm unable to drop weapons when practice mode is enabled. Neither primary nor secondary weapons work for me. You can drop the C4 though.

### Expected behavior
Weapon is dropped so that your teammates can pick it up.

### Actual behavior
Weapon is not dropped.

### Steps to reproduce
- Plugin version: 1.3.3
- Sourcemod version: 1.9.0
- Steps to reproduce (please be specific):
   1. Buy a weapon
   2. Press your "drop weapon" key

**Comment by splewis** [comment]
That's because `mp_death_drop_gun` is set to 0 by default. You can change it in your config, if you want: https://github.com/splewis/csgo-practice-mode/blob/master/configs/practicemode.cfg#L39

**Comment by cybersteel8** [comment]
@splewis I would like to follow up on this query.
When a gun is dropped by changing `mp_death_drop_gun` to 1, why does the gun disappear when it lands on the ground? Is there a setting for this too?
