### ISSUE TITLE
sm_autostart_practice 

### ISSUE THREAD

**Issue by icecoldf** [splewis/csgo-practice-mode#122]
I'm having trouble enabling the sm_autostart_practice, I can't figure out where I should be using this convar. I've tried it in the server.cfg as well as in the practicemode.cfg but neither seemed to have any effect. I've also tried changing the .sp to 1 instead of 0 but that too changed nothing. Any help would be appreciated,

**Comment by AG4lyf** [comment]
" You can edit these in the file cfg/sourcemod/practicemode.cfg, which is autogenerated when the plugin first starts. "

https://github.com/splewis/csgo-practice-mode#convars

**Comment by splewis** [comment]
practicemode.cfg is correct, but the cvar has issues and I wouldn't rely on it working: see #46. It's more likely to be removed than fixed at this point, I suspect.
