### ISSUE TITLE
bot commands

### ISSUE THREAD

**Issue by basse27** [splewis/csgo-practice-mode#124]
i will like to have the change for me to get the bot to shoot against you where they are addet that way it it will be the perfect training map for me i have tryed to put ind the command bot_dont_shoot bot i cant have acces to it 

hope you can helt me ore maybe make it so i can youse it ore maybe telle me how tto do it

**Comment by AG4lyf** [comment]
its bot_stop 
You can configure practicemode.cfg
to add a option to toggle it , 
I hope thats what you wanted

**Comment by splewis** [comment]
Sorry, making the bots shoot back isn't a feature yet. I can't tell you how to implement it, either.
