### ISSUE TITLE
How can I increase the number of recorded grenades beyond 512?

### ISSUE THREAD

**Issue by donvitocsgo** [splewis/csgo-practice-mode#125]
Hi, I reached the maximum number of grenades per-map (512). How can I increase the number of recorded grenades beyond 512?

**Comment by splewis** [comment]
https://github.com/splewis/csgo-practice-mode#convars

Changing the value for `sm_practicemode_max_grenades_saved` in `cfg/sourcemod/practicemode.cfg` should do it (it should say 512 now, just change to that 10000 or whatever you want).

**Comment by splewis** [comment]
fyi, I also just pushed a change so that you can set the cvar to 0 to disable the max altogether in future versions: https://github.com/splewis/csgo-practice-mode/commit/e66b1010d6e7d3d595460424fb7d29327810616b

**Comment by donvitocsgo** [comment]
@splewis Thank you so much man! Your job is awesome!
