### ISSUE TITLE
!prac command problem

### ISSUE THREAD

**Issue by boXseven** [splewis/csgo-practice-mode#126]
### Expected behavior
typing !prac in chat, menu shows up, i close it (exit), type !prac again and menu shows up again

### Actual behavior
typing !prac in chat, menu shows up, i close it (exit), type !prac again and menu **doesnt** show up

### Steps to reproduce
- Plugin version: "sm_practicemode_version" = "1.3.3"
- Sourcemod version: SourceMod Version: 1.9.0.6281
- Steps to reproduce (please be specific):
type !prac in chat, close the menu, type !prac again

**Comment by boXseven** [comment]
ok, i mean u can use .setup to exit the prac mode but wouldnt it be a good idea to use !prac as a toggle?

**Comment by splewis** [comment]
The command is mapped to "launch practice mode", so I don't expect to change it. There is a separate exit practice mode command.

**Comment by boXseven** [comment]
> 
> 
> The command is mapped to "launch practice mode", so I don't expect to change it. There is a separate exit practice mode command.

I don't know if I am blind, but I just couldn't find such a prac exit command in the documentary.
Which one is it?
