### ISSUE TITLE
When .throw <smoke> is used and mollies are thrown into it, they burn.

### ISSUE THREAD

**Issue by stealthrs** [splewis/csgo-practice-mode#127]
Smokes deployed by .throw <id> don't put out mollies that are thrown into them.

### Expected behavior

When .throw <smoke> is used, the smoke pops, and a molly is thrown into it, it should be extinguished.

### Actual behavior

When .throw <smoke> is used, the smoke pops, and a molly is thrown into it, the molly burns.  The popped smoke doesn't put it out.

### Steps to reproduce
- Plugin version: 1.3.3
- Sourcemod version:  1.9.0.6276
- Steps to reproduce (please be specific):  Type .throw 1 (assuming it's a smoke that lands).  Throw a molly into it... Watch it burn!!!

**Comment by splewis** [comment]
Added to the list of reasons the fake smokes used aren't ideal in #71.

It's probably unlikely that someone fixes this issue, unfortunately.
