### ISSUE TITLE
Allow to lock .setup and .practice commands in order to be runned by only an admin

### ISSUE THREAD

**Issue by ludo237** [splewis/csgo-practice-mode#13]
Hello.

As the title said, is it possible to lock up the commands?

**Comment by splewis** [comment]
pugsetup sets permissions through a pugsetup-specific config file: [configs/pugsetup/permissions.cfg](https://github.com/splewis/csgo-pug-setup/blob/master/configs/pugsetup/permissions.cfg).
You could change ``sm_setup`` to ``admin``.

.practice isn't a pugsetup command,  so you'd have to go through the normal [sourcemod command overrides](https://wiki.alliedmods.net/Overriding_Command_Access_(Sourcemod)). Unfortunately I didn't to give 3 forms for that command so you'd have to add a restriction on all 3: ``sm_launchpractice``, ``sm_practice``, ``sm_prac`` (these are map-change flag admin by default).

**Comment by ludo237** [comment]
Wow cool. Thank you for this !

**Comment by emko** [comment]
sorry  dumb question am i doing this right? im trying to block non admins from using .setup / .practice

`   	"sm_practice" "b" 
	"sm_launchpractice" "b"
	"sm_prac" "b"
`
