### ISSUE TITLE
sm_practicemode_fastforward_requires_zero_volume 1 is a massive issue

### ISSUE THREAD

**Issue by mrsaggyman** [splewis/csgo-practice-mode#131]
i am so annoyed. you implemented STUPID COMMAND. i had to create a github account just to vent. cant even change this cvar in practicemode.sp doesnt apply in game. i have to manually change the cvar my self to make .ff work you sack of pretzals

**Comment by splewis** [comment]
You're supposed to edit the cfg/sourcemod/practicemodr.cfg file like the readme tells you.

If you edit the file you're just changing the cvar value's default (assuming you're also recompiling the plugin, without that any source code changes do nothing).

> you sack of pretzals

Nice.
