### ISSUE TITLE
Plugin crashes server after Shattered Web update.

### ISSUE THREAD

**Issue by Blacktail92** [splewis/csgo-practice-mode#135]
### Expected behavior

Normal behavior as intended.

### Actual behavior

Using plugins `practicemode.smx` and/or `botmimic.smx` results in server crash (srcds.exe) after Shattered Web update. I think that's because of the newly added player models, not certain though. With the plugins disabled/removed, there is no issue.

All components mentioned below are up to date as of 25/11/2019.

### Steps to reproduce
- Plugin version: 1.3.3
- Sourcemod version: 1.9.0.6282
- client version: 1.37.2.6
- server version: 1.37.2.6
- sm_botmimic_version: 2.1
- sm_csutils_version: 1.3.3

Steps to reproduce (please be specific): 
- Load either/both of the mentioned plugins to the server.
- Join the server.
[console_output.txt](https://github.com/splewis/csgo-practice-mode/files/3886954/console_output.txt)

**Comment by cybersteel8** [comment]
Related #133

**Comment by Blacktail92** [comment]
Updated sourcemod. Problem solved.
