### ISSUE TITLE
If Practicemode.smx is loaded, the server freezes and you get a connection problem

### ISSUE THREAD

**Issue by xnimoCS** [splewis/csgo-practice-mode#137]
Using the newest stable MetaMod and the newest stable SourceMod aswell as the newest practicemode. Is the version not compatible with the newest versions of mm and sm?

Kind regards
nimo

**Comment by splewis** [comment]
>Is the version not compatible with the newest versions of mm and sm?

If you're having server problems - the sourcemod & metamod versions are vastly more likely to be the problem. Update sourcemod to a newer build and things will probably work again: https://www.sourcemod.net/downloads.php

**Comment by splewis** [comment]
Closing, no evidence there's a real practicemode problem still.
