### ISSUE TITLE
.ff not working properly

### ISSUE THREAD

**Issue by Flucky2** [splewis/csgo-practice-mode#138]
.ff is working but the smokes are taking a really long time to go away I switched server providers and now this happens

**Comment by splewis** [comment]
All the `.ff` command really does is set the `host_timescale` cvar: https://github.com/splewis/csgo-practice-mode/blob/ed83f44a5b370f68261119a13e3658105cad8704/scripting/practicemode/commands.sp#L238-L240

It's possible your host is breaking that cvar somehow.
