### ISSUE TITLE
Grenades is not saving in my server folder

### ISSUE THREAD

**Issue by linkito** [splewis/csgo-practice-mode#14]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

When write .save xxxx, the position must be saved in a file on "csgo/addons/sourcemod/data/practicemode/grenades"

### Actual behavior

When write .save xxx, I can view my saved grenades writing .nades, but if I exit from the server and reconnect again, when I wrote .nades, no saves are available. Also, on the server, the grenades folder is empty...

I have the folder with 0777 CHMOD, on a Linux Server

### Steps to reproduce
- Plugin version: 1.1.0
- Sourcemod version: 1.8.0.5928

**Comment by splewis** [comment]
Have you checked for any error logs? ``addons/sourcemod/logs``

**Comment by splewis** [comment]
Closing since there's no response and I can't reproduce any bug.

**Comment by bykidi** [comment]
@splewis it seems like it was folder access problem and he fixed it by himself.
