### ISSUE TITLE
Edit Smokes Later

### ISSUE THREAD

**Issue by mcsnack** [splewis/csgo-practice-mode#140]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Ich würde mir eine Funktion Wünschen in der Ich Smokes Später Bearbeiten kann, wie zum Beispiel diese zu einem Späteren Zeitpunkt einer Kategorie zuzuordnen. !nadeaddcats [SMOKE ID] [CATNAME]

### Actual behavior
I Can´t find the function.

### Steps to reproduce
- Plugin version: 1.3.3
- Sourcemod version:VERSION: 2019-9-30
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
Please post issues in English. I cannot help otherwise.

**Comment by mcsnack** [comment]
iám Sorry I would like a function in which I can edit Smoke's Later, such as assigning it to a category later. ! nadeaddcats [SMOKE ID] [CATNAME]

**Comment by splewis** [comment]
https://github.com/splewis/csgo-practice-mode#modifying-a-saved-grenade

You can `.goto <id>`, then `.addcat <category name>`.

**Comment by mcsnack** [comment]
Thank you for the quick help!
Can you delete saved smokes?

**Comment by splewis** [comment]
Yes, as the readme says https://github.com/splewis/csgo-practice-mode#saving-grenade-positions:

```.delete: deletes the last grenade of yours that you used .goto (or .nades) to teleport to```
