### ISSUE TITLE
bots don't crouch / other issues.

### ISSUE THREAD

**Issue by MikkelDK** [splewis/csgo-practice-mode#141]
Hi. 

There is some weird bug with csgo-practice mode.

I did insert - 2 videos to document, what the problem I'm talking about =D
### Expected behavior:
Problems with crouch-bot on the plugin.
Problems with bot don't "place" as you stand.
You can't hit "head" on the bot. (hitbox?)

### Actual behavior:
When I place A bot, if I look on the left side (looking from T-spawn to pit.) so the bot should look(place) the same way, as I stand/looking after. (**Are bots ONLY supposed to look straight ahead when you are in a different angle/direction or look backward **?)

When I place A bot, of "crouch" **it doesn't DUCK or CROUCH**
If you are hitting on the bot (at head) = it doesn't hit.

### Steps to reproduce:
- Plugin version: **1.3.4-dev+299**
- Sourcemod version: **1.10.0.6460**
- Steps to reproduce (please be specific): Join the gameserver, load csgo-practicemode and doing place:

.bot (ingame the server) - it looking "straight", also if you are looking on dif angle/direction.
.crouchbot (ingame the server) - it should do "duck/crouch" but it's only stand up, as ".bot" place do.

Buy AK47 > Hit on the head => hitbox bugged???

**Video 1 (Problems with crouch/stand, and how I'm looking at a dif angle/direction.):**
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/22q4tU4yndo/0.jpg)](http://www.youtube.com/watch?v=22q4tU4yndo)

**Video 2 (AK47 > Hit at head at bot => Hitbox bugged):**
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/seuH_7ikMY0/0.jpg)](http://www.youtube.com/watch?v=seuH_7ikMY0)

**Comment by minim0vz** [comment]
did you found a fix for this issue ? i am having the same results as yours and i think it might be related to bots not working on linux servers

**Comment by MikkelDK** [comment]
> did you found a fix for this issue? I am having the same results as yours and i think it might be related to bots not working on Linux servers

Yeah @minim0vz I did solve it. =) 
[practicemode.zip](https://github.com/splewis/csgo-practice-mode/files/4923700/practicemode.zip) < Here these .smx work =)

**Comment by minim0vz** [comment]
@MikkelDK I will check it out in a few hours, thanks in advance, i will respond again if it works or not

**Comment by minim0vz** [comment]
@MikkelDK it appears to not have fixed my issue, bots are behaving exactly like the video, they spawn with no weapons, always looking at 0º on Y axis and gliteched hitbox

**Comment by MikkelDK** [comment]
@minim0vz let me try to send the fully .zip =)

[practicemodev2.0.zip](https://github.com/splewis/csgo-practice-mode/files/4927635/practicemodev2.0.zip)

It should work, it works for me. I use it on 15 csgoservers.

**Comment by splewis** [comment]
Please do not post smx files without the source code attached. It's against the GPL license sourcemod derivative works fall under: https://www.sourcemod.net/license.php.

**Comment by minim0vz** [comment]
Just an update, that zip you sent above that was link removed didn't work for me too, i don't know what it is now, bots are only working on windows dedicated servers.

**Comment by MikkelDK** [comment]
> Just an update, that zip you sent above that was link removed didn't work for me too, i don't know what it is now, bots are only working on windows dedicated servers.

@minim0vz - Do it buggy still if you download dev version and use the version?
http://ci.splewis.net/job/csgo-practice-mode/lastSuccessfulBuild/ < dev version here ^^

**Comment by minim0vz** [comment]
Still same problems, today i discovered that the dhooks from the server was outdated and was not loading, so i updated it and problem still happens so it's something else causing the issue

**Comment by minim0vz** [comment]
@splewis do you have any idea why this happens ? i also posted a unique post to my issue at #158

**Comment by splewis** [comment]
No, I don't know why it happens. Debugging these types of things tends to be trial-by-error. If there's a difference in linux vs windows behavior, there may be a deeper issue (i.e. outside of the practicemode plugin) causing it.

**Comment by minim0vz** [comment]
hmm i don't know what it is then, this is the second or third server provider that i am using and the problem appeared on all of them, there is something wrong with the bot spawning method on linux maybe, if someone can confirm this it would be great, the strange thing is that the replay mode works without errors

**Comment by Corrreia** [comment]
Is there any news on this topic? I also have this problem.

**Comment by minim0vz** [comment]
haven't found a solution, i just completely gave up

**Comment by MikkelDK** [comment]
> haven't found a solution, i just completely gave up

It works for me now.
Try to download the dev version: [dev version 303](https://ci.splewis.net/job/csgo-practice-mode/lastSuccessfulBuild/artifact/builds/practicemode/practicemode-303.zip).

Do this:
place csutils.smx on "plugins" folder AND "plugins/disabled"
place botmimic.smx on plugins
place practicemode.smx on plugins.

Restart the gameserver
And it should work. (it works for me; since I'm hosting 100 gameservers per day)

**Comment by Corrreia** [comment]
I will try it then I will leave feedback.

**Comment by Corrreia** [comment]
It didn't work for me ://  I already had everything on those directories except the cs.utils.smx on the "plugins/disabled".
Anyway, ty so much for the help. if you think I'm doing anything wrong tell me.

**Comment by MikkelDK** [comment]
Strange, it don't work. And you did installed folders to the folders?

I'm willing to try install it correct and test for you on your server eg.

**Comment by Corrreia** [comment]
I'm going to add you on steam.

**Comment by MikkelDK** [comment]
> I'm going to add you on steam.

Accepted.

**Comment by Makaren0** [comment]
> > haven't found a solution, i just completely gave up
> 
> It works for me now. Try to download the dev version: [dev version 303](https://ci.splewis.net/job/csgo-practice-mode/lastSuccessfulBuild/artifact/builds/practicemode/practicemode-303.zip).
> 
> Do this: place csutils.smx on "plugins" folder AND "plugins/disabled" place botmimic.smx on plugins place practicemode.smx on plugins.
> 
> Restart the gameserver And it should work. (it works for me; since I'm hosting 100 gameservers per day)

Not working for me, still trying to find the way to make it works. Can u guys help me?

**Comment by mrc4tt** [comment]
> Not working for me, still trying to find the way to make it works. Can u guys help me?

@Makaren0 - Sorry. I can't help as this was over 1 year ago. It works fine for me.

You can try installing dev **or** stable.
stable: https://github.com/splewis/csgo-practice-mode/releases/download/1.3.4/practicemode_1.3.4.zip
dev: https://ci.splewis.net/job/csgo-practice-mode/lastSuccessfulBuild/artifact/builds/practicemode/practicemode-322.zip

Remember to check that you have installed it correctly.

**Comment by Makaren0** [comment]
@mrc4tt Does it currently work for you? wow. Do you remember which version you used? For me both do not solve the problem, the bots appear with fixed angles and without a weapon. Quite strange that this continues, something weird must have happened with the updates. Could you remember something that the good colleague @corrreia told you? Thanks alot for every information, i really need this :D

**Comment by Makaren0** [comment]
I definitely found my problem (I have no idea if this is replicated in another setup).
When I use workshop maps and use ".bot" everything is broken, but when I disable the use of the workshop the bots are positioned correctly as expected. What a simpler thing...
