### ISSUE TITLE
bots flashed reset

### ISSUE THREAD

**Issue by wooliehero** [splewis/csgo-practice-mode#144]
hey there, love this addon, so handy.

just had a request - when a bot gets blind their arm stays up showing they are blind, could we have options to reset bots so we can easily see which are blind and which aren't?

possibly also have the arm represent accurately how long the bot is blind for, could be good.

Thanks!

**Comment by Jasperhino** [comment]
see #79

**Comment by splewis** [comment]
I doubt these will be fixed anytime soon (or ever), but yes: https://github.com/splewis/csgo-practice-mode/issues/79
