### ISSUE TITLE
Bot spawning transparent ( immune to damage )

### ISSUE THREAD

**Issue by bebou5** [splewis/csgo-practice-mode#146]
Hello, any idea why almost all bots I spawn are transparent and so immune to damage ? 
![image](https://user-images.githubusercontent.com/62607067/77436973-6a343980-6de4-11ea-85c9-ce001495b2c3.png)

Thnak you for this amazing mod !

**Comment by bebou5** [comment]
![bots](https://user-images.githubusercontent.com/62607067/77437242-ba130080-6de4-11ea-8e85-604e5ad6954a.jpg)

**Comment by stealthrs** [comment]
Hey, I ran into this and it stumped me for a little bit... I ended up fixing it and I cannot remember how off the top of my head...  I believe it was a setting in the server.cfg file.  I'm away from my main PC; but, I'd be able to rack my brain a little more tomorrow.

Do you want to post up your server's configs for server.cfg and practicemode.cfg?  Scrub the rcon password out.

**Comment by splewis** [comment]
I would guess one of the spawn immunity cvars is doing this.

If you're launching your server as casual (`game_mode 0`) instead of competitive (`game_mode 1`), that might be why the cvar is set that way. If that's the case, you should probably just launch the server as competitive so it uses those default cvar values.

**Comment by stealthrs** [comment]
I think that's it!  In my case, I had the custom game mode cfg running (gamemode_custom.cfg) The gamemode_competitive.cfg wasn't being run.  If your server is hosted, there may be an option on the site's web control panel to set the game mode to Competitive.

**Comment by bebou5** [comment]
Ok ! Thank you for the replies guys. I don't have acces to modify the launcher and my server is set to casual mode with a modified gamemode_casual_server.cfg close to competitive with some personnal tweaks.
I will try to change the game_mode to 1 and restart the map until it says 'competitive' during the loading screen and than launch the practice mod.
I will let you know if this works.
[server.cfg.txt](https://github.com/splewis/csgo-practice-mode/files/4444359/server.cfg.txt)
[practicemode.cfg.txt](https://github.com/splewis/csgo-practice-mode/files/4444360/practicemode.cfg.txt)

**Comment by Entita** [comment]
Greetings, 
I have the same problem now, it worked fine in the past, but even when I'm on competitive mode most of them are transparent, do you have any idea how to fix it? 
Thank you, Jacob.

**Comment by bebou5** [comment]
Edit : For me, going into competitive, never solved the problem ^^

**Comment by splewis** [comment]
Have you checked to see what the value of `mp_respawn_immunitytime` is? My theory was that spawn immunity being enabled is the issue. Practicemode doesn't touch that cvar by default, so if it's left to a non-zero value by some other plugin/config that might cause this.

**Comment by Entita** [comment]
I checked and I have value of mp_respawn_immunitytime 5, so I will change it, but my server hosting is having some troubles now, so I will get you know then. Thank you.

**Comment by Entita** [comment]
mp_respawn_immunitytime 0 worked, thank you !

**Comment by bebou5** [comment]
Thank you splewis !
