### ISSUE TITLE
Add more than 2 spectator slots

### ISSUE THREAD

**Issue by idderf** [splewis/csgo-practice-mode#15]
At the moment we are only able to have 2 people in spectators, even though we have set the cvar mp_spectators_max to 5.

We use practice plugin with my team when our leader wants to show us strats and nades.
This is, however, difficult to do since we can't have 4 people in spec + 1 on a team.

Can you somehow add support for 5 spectator slots in this plugin?

Thanks

**Comment by splewis** [comment]
This plugin doesn't restrict teamjoins at all. You should verify mp_spectators_max is what you think it is (``sm_cvar mp_spectators_max`` in console will tell you the value)

In fact, if practicemode is enabled (is it?) it will let anyone join any team: https://github.com/splewis/csgo-practice-mode/blob/master/scripting/practicemode.sp#L487

**Comment by splewis** [comment]
Closing since there's been no response and I don't believe there's a bug here.
