### ISSUE TITLE
Changed MESSAGE_PREFIX to Server Name - Plugin Breaks on new map

### ISSUE THREAD

**Issue by stealthrs** [splewis/csgo-practice-mode#150]
Trying to change the natives.sp file by editing the message prefix.

#define MESSAGE_PREFIX "[\x0CThe Practice Farm\x01]"

### Expected behavior
Change the prefix from [PracticeMode] to [The Practice Farm] without there being any unintended consequences.

### Actual behavior
It works fine at first, because the name changes and so do the colors.  But... When the server's map changes, the buy zones break, the bots go invisible, buy times and round times apply, and PracticeMode doesn't turn off.  Not sure what else breaks.  It just acts like PracticeMode has a "hangover" into the next map and never can start in the next map, and the server's configs and preferred game_mode supersedes. 

I had this problem before I had tonight's compiling issues the botmimic.inc.

### Steps to reproduce
- Plugin version: 1.3.4-299 (except I fixed that bum include file mentioned in the other thread.
- SourceMod version: 1.10-6455
- Steps to reproduce (please be specific):
1) Edit the natives.sp file to a new name and/or color
2) Compile
3) Install the new .smx
4) Boot up the server and all is fine 
5) Join the server and change the map
6) Wait 20 seconds (assuming mp_buytime is set to 20)
7) Test buying, buyzones, and infinite ammo. Test respawning. Spawn some bots.  Stuff is broken!

Is there anything that's relying upon the MESSAGE_PREFIX being "PracticeMode"?

**Comment by splewis** [comment]
No, there should be no dependency on the prefix. Do you see issues with the dev builds provided?

**Comment by stealthrs** [comment]
> No, there should be no dependency on the prefix. Do you see issues with the dev builds provided?

Yeah... This one is on me... I found some missing code in the practicemode.sp.  Sorry for bothering.

**Comment by LuxeLife** [comment]
I cant change my prefix, i need help :(
