### ISSUE TITLE
talk to enemy team

### ISSUE THREAD

**Issue by Ishaan-Kumar** [splewis/csgo-practice-mode#152]
Pug setup plugin is also installed on server
When !setup > Launch Practice Mode is clicked
Players cannot talk to players in other team? How to enable it?

**Comment by splewis** [comment]
You could add the cvars to your config in `configs/practicemode.cfg`

There's some cvars it automatically sets when you launch practicemode: https://github.com/splewis/csgo-practice-mode/blob/master/configs/practicemode.cfg#L28-L44

You could add to that
```
"sv_alltalk"  "1"
```

or whatever other cvars you want.
