### ISSUE TITLE
.ff removing the "all must be at volume 0.01 or less" requirement

### ISSUE THREAD

**Issue by AmjedAgabani** [splewis/csgo-practice-mode#155]
hi, tried to modify the commands.sp file to remove the 0.01 volume or less requirement - not working so well for me.

i've modified it to look like this

```
 if (g_FastfowardRequiresZeroVolumeCvar.IntValue != 0) {
    // for (int i = 1; i <= MaxClients; i++) {
      // if (IsPlayer(i) && g_ClientVolume[i] > 0.01) {
        // PM_Message(client, "All players must turn volume below 0.01 to allow the .ff command.");
        // return Plugin_Handled;
      // }
    // }
    PM_Message(client, "Not all players have volume below 0.01 but .ff command executed anyway. To reenable sound protection check sourcemod/scripting/practicemode/commands.sp file.");
  }
```

however same functionality still remains - any idea if i'm missing something?

**Comment by rodrigo-apoc** [comment]
> hi, tried to modify the commands.sp file to remove the 0.01 volume or less requirement - not working so well for me.

"You can edit these in the file cfg/sourcemod/practicemode.cfg, which is autogenerated when the plugin first starts."

// Whether all players must have a very low volume to allow the .ff command to be used.
// -
// Default: "1"
sm_practicemode_fastforward_requires_zero_volume "1"

**Comment by AmjedAgabani** [comment]
Thanks.
