### ISSUE TITLE
Add freezetime after tp

### ISSUE THREAD

**Issue by tiibzbe** [splewis/csgo-practice-mode#16]
Hi,

It would be usefull if you add a freezetime after a teleportation to prevent mouse movement!

Thanks for your awesome plugin

**Comment by splewis** [comment]
I think this would be fine to add, it'd probably be a client setting saved by a sourcemod cookie like some other "advanced" settings: https://github.com/splewis/csgo-practice-mode/wiki/Overview-of-Commands#client-settings-cookies

**Comment by splewis** [comment]
Having tried this, locking mouse movement from a server plugin doesn't seem possible to do reliably.

The server can move your crosshair back each frame, but it ends up being very glitchy and is a poor user experience, so I'm not going to add this. Sorry.
