### ISSUE TITLE
sm_setup instead of .setup or sm_prac

### ISSUE THREAD

**Issue by Ramiretee** [splewis/csgo-practice-mode#168]
Hello, I wanted to know if it is possible to add a sm_setup to be able to bind on a key, instead of sm_prac or write in the chat .setup
thz

**Comment by splewis** [comment]
Does adding `bind x sm_setup` in your client console fit your needs here?

**Comment by Ramiretee** [comment]
no, that's why i wrote here. there isnt a sm_setup command, and i dont known how to make it.
it is possible to is it possible to create the command?

**Comment by splewis** [comment]
Ah, right. I forgot practicemode doesn't natively have a `sm_setup` command.

You could bind any of these though (they behave the same, the 1st just prints to chat):

``bind x say .prac``
``bind x sm_prac``


> edit: also, theres a command to be able to drop weapons?

You can remove `mp_death_drop_gun` from your `addons/sourcemod/configs/practicemode.cfg` file if you want: https://github.com/splewis/csgo-practice-mode/blob/e7c68515f97b81b4b0c92cf4cb9f85ebfcb80e75/configs/practicemode.cfg#L39. That cvar has the effect of disallowing weapon drop commands.

**Comment by Ramiretee** [comment]
thanks for the mp_death_drop_gun.
the issue with sm_prac is that I can only use it once, then it won't open, and practice mode is executed.
my idea is to have the bind on a key, to change options, and eliminate the practice mode.

But don't worry it's a bad habit of mine to bind everything.

**Comment by splewis** [comment]
There is a `sm_exitpractice` command.  But if you're after a toggle command (I think that's what you're looking for), there isn't one yet.

**Comment by Ramiretee** [comment]
thanks for the response splewis, you can close it now
