### ISSUE TITLE
[help] compile issue

### ISSUE THREAD

**Issue by rodrigo-apoc** [splewis/csgo-practice-mode#169]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Compile lastest Practicemode.

### Actual behavior
There are 2 includes that just doesn't exist if I want to use only Practicemode.
```
#include <get5>
#include <pugsetup>

```
Even if I comment these lines, there are several mentions to PugSetup around the files of Practicemode.
I would like to make some changes in code and see how it goes on server.
If I just comment all the mentions about PugSetup it'll be fine? or is it needed in fact to have get5/pugsetup to compile practicemode completely?

Also, what about creating a discord server so users can talk each other about your plugins, getting help, etc...

**Comment by splewis** [comment]
Fyi, there are reproducible steps for all that is needed to compile at https://github.com/splewis/csgo-practice-mode/blob/master/.travis.yml.

Those specific includes can be gotten from:
- https://raw.githubusercontent.com/splewis/csgo-pug-setup/master/scripting/include/pugsetup.inc
-  https://raw.githubusercontent.com/splewis/get5/master/scripting/include/get5.inc

**Comment by rodrigo-apoc** [comment]
> Fyi, there are reproducible steps for all that is needed to compile at https://github.com/splewis/csgo-practice-mode/blob/master/.travis.yml.

Yeah I'm so sorry for make a dumb question.
I just saw travis.yml file a few minutes after I did open the Issue.

**Comment by rodrigo-apoc** [comment]
Also @splewis what do you think of a Discord server for people who follow your work?
It may be helpfull to talk to others people, asking help, sharing codes, etc..
