### ISSUE TITLE
Add subcategory in menu

### ISSUE THREAD

**Issue by tiibzbe** [splewis/csgo-practice-mode#17]
Hi again,

It would be usefull too if you add subcategory in the menu when you type .cats or .nades.

It would be easier too sort. For exemple we could have 3 category : Molotovs , Smokes and Flashs and in each category we could add few categories, for exemple : CT , T or Mid , Long , Short etc etc etc

**Comment by splewis** [comment]
Sorry, I don't think this will be added. The whole category system is already a bit of a mess, and I'd rather avoid complicating it moreso.
