### ISSUE TITLE
Export saved grenades for backup purposes

### ISSUE THREAD

**Issue by MichaelRanftelhuber** [splewis/csgo-practice-mode#171]
Dear practice-mode community,

I am looking for a simple way to export & save the database of saved nades of the practice mode.

Explanation: Due to some issues in combination with eBot, I had to reinstall practice mode on our server recently and thereby lost all my grenades. I do, however, still have an old copy of the server files.

Could you maybe either implement a simple backup option or point me to the required files (one of the mysql database files, I guess?) that I need to backup and then copy into my new installation?

I have over 200 saved grenades and I keep forgetting quite some of them, so this would be an awesome improvement!

Thanks a lot!

Yours,

Michael

**Comment by zahti** [comment]
I would like to know where these grenades are saved as well! I recently setup a practice server on NFO Servers but the quality of the host is pretty poor. I would like to transfer these saved grenades to the server I have hosted on dathost and need to figure out the right file to transfer (if possible)!

**Comment by Otoris** [comment]
Check out your addons/sourcemod/data folder. They should all exist in text files inside of there.

**Comment by splewis** [comment]
See https://github.com/splewis/csgo-practice-mode/wiki/How-your-data-is-stored#moving-data-to-a-new-server

**Comment by MichaelRanftelhuber** [comment]
Dear zhati, dear splewis,

thanks a lot! I will simply backup the folder "counterstrike_go/csgo/addons/sourcemod/data/practicemode" completely on a regular basis.

If I understood you correctly, I can simply overwrite these files on a new (clean) server and will get my nades back? Thanks a lot!

Yours,

Michael

**Comment by splewis** [comment]
> If I understood you correctly, I can simply overwrite these files on a new (clean) server and will get my nades back?

Correct.
