### ISSUE TITLE
I'm unable to load the plugin on SM

### ISSUE THREAD

**Issue by Pyrolaxian** [splewis/csgo-practice-mode#173]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Plugin Loads

### Actual behavior
Plugin doesn't load, and errors with "[SM] Plugin practicemode.smx failed to load: Unable to open file."

### Steps to reproduce
- Plugin version: 330
- Sourcemod version: 1.10.0.6501
- Steps to reproduce (please be specific):
- Type "sm plugins load practicemode"

**Comment by splewis** [comment]
You probably have a filesystem error reading the file - maybe lack of read permissions for the user running the CS:GO server?

**Comment by Pyrolaxian** [comment]
> You probably have a filesystem error reading the file - maybe lack of read permissions for the user running the CS:GO server?

How would I go about fixing this? I'm running this via my own PC.

**Comment by Pyrolaxian** [comment]
Fixed!
