### ISSUE TITLE
Spam Client

### ISSUE THREAD

**Issue by oqyh** [splewis/csgo-practice-mode#174]
any fix for client spam 
Thank You!

https://user-images.githubusercontent.com/48490385/103039892-64de6800-458b-11eb-8831-6ce26ca05673.mp4

**Comment by splewis** [comment]
I haven't seen this issue.

Can you fill out the issue template? It's extremely hard to help people if they don't provide basic information on how to reproduce an issue:
```
### Steps to reproduce
- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):
```

**Comment by oqyh** [comment]
- Plugin version: 1.3.3
- Sourcemod version: 1.10
- Steps to reproduce (please be specific): as in the video clients can spam nads/smokes/molly by typing in console [bind k "sm_throw"] throw any nade then spam pressing k will spam nades like as shown in the video this my server for test 15.184.55.170:27015

**Comment by oqyh** [comment]
i fixed it with my own plugin
