### ISSUE TITLE
.ff Volume 0.01

### ISSUE THREAD

**Issue by midnightcatzz** [splewis/csgo-practice-mode#176]
Hi, is there anyway to disable this feature? i actually would love that i can play with volume more than 0.01 to use the .ff function . thanks !

**Comment by splewis** [comment]
You can set `sm_practicemode_fastforward_requires_zero_volume` to 0 in `cfg/sourcemod/practicemode.cfg`.

**Comment by midnightcatzz** [comment]
thanks alot . !
