### ISSUE TITLE
Is there a possibility to get the default Grenade Trajectorys back?

### ISSUE THREAD

**Issue by phnxde** [splewis/csgo-practice-mode#179]
So there is this command in the practicemode.cfg 
"sm_grenade_trajectory_use_player_color"	"0"
### Expected behavior
The Player Color gets set to its ingame color if on 1
If on 0, it's just green.

### Actual behavior
Thats working and so on, but these aren't the same grenade trajectory as the defaults from CS:GO, is there a way to bring them back?

**Comment by splewis** [comment]
> but these aren't the same grenade trajectory as the defaults from CS:GO, is there a way to bring them back?

No. The default csgo grenade trajectories do not work on online servers, only on self-hosted "listen" servers (i.e. when you type 'map de_mirage in console's). It would require Valve to fix that. That's why practicemode had its own trajectories.
