### ISSUE TITLE
How to modify the .map listing ?

### ISSUE THREAD

**Issue by iamAXO** [splewis/csgo-practice-mode#184]
Hi there,

Might be a really simple answer for you guys but, I can't figure out how do I change the listing of maps when we type .map
It's all default map and I want to add/remove some.

Thanks

**Comment by splewis** [comment]
Edit your `addons/sourcemod/configs/practicemode.cfg` file: https://github.com/splewis/csgo-practice-mode/blob/37b32364f1f9f08a4dba90bd91446b1de516f012/configs/practicemode.cfg#L14-L24

**Comment by iamAXO** [comment]
Thanks! I'm blind haha
