### ISSUE TITLE
Cant delete catagory

### ISSUE THREAD

**Issue by ZerXGIT** [splewis/csgo-practice-mode#190]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
deleting the catagory.

### Actual behavior
command: .deletecat xyz
output: catagory not found.

### Steps to reproduce
- Plugin version: 1.3.3
- Sourcemod version:  1.10 (I think) i have the newest version.
- Steps to reproduce (please be specific):
just try to delete a catagory.

**Comment by karmicdude** [comment]
+1 the same behavior
