### ISSUE TITLE
Glitch in Line 1167 practicemode.sp, no "practicemode_start.cfg"-file (version 1.3.3)

### ISSUE THREAD

**Issue by ElCurioso** [splewis/csgo-practice-mode#195]
Found a contradiction in practicemode.sp version 1.3.3

line 1089:
  BuildPath(Path_SM, filePath, sizeof(filePath), "configs/**practicemode**.cfg");

line 1166:
  ServerCommand("exec sourcemod/**practicemode_start**.cfg");

I am no Pro, but shouldn't the cfg-files have the same name?

**Comment by splewis** [comment]
Those are two different config files.

The first is parsed as keyvalues for practicemode specific configuration: https://github.com/splewis/csgo-practice-mode/blob/ebadb0383a00b28ad58d42de134a333d4300f39e/scripting/practicemode.sp#L1107-L1110

The 2nd is the execution of a config the user can arbitrarily configure with any commands/cvars they want, hence not parsing it, but performing a raw "exec" command on it.

**Comment by ElCurioso** [comment]
Thank you so much for your fast reply.

You thought of everything. Such a powerful plugin, awesome!

_My practicemode_start.cfg: in ...csgo\cfg\sourcemod_
sm_headshotonly_enabled "0"
echo headshot-only DISABLED

_My practicemode_end.cfg: in ...csgo\cfg\sourcemod_
sm_headshotonly_enabled "1"
echo headshot-only ENABLED

**Works like a charm!**

I only spotted the tip of the iceberg yet, but I already love this plugin.

Issue solved, again, thank you so much!
