### ISSUE TITLE
Show damage when using grenade

### ISSUE THREAD

**Issue by Alex-dengxz** [splewis/csgo-practice-mode#197]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

I hope if I set a bot, when  I use grenade, the bot will show the damage.

### Steps to reproduce
- Plugin version:1.3.3
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by PlamAtom** [comment]
So it does not show in text for example:
[PracticeMode] ---> 95 damage to BOT PlamAtom (99 health)                                  // Shoot example
[PracticeMode] ---> 45 damage to BOT PlamAtom (45 halth)                                  // Grenade example

**Comment by splewis** [comment]
I can't reproduce this; I see the damage. Let me know if there's still a bug on recent versions.
