### ISSUE TITLE
i cannot connect

### ISSUE THREAD

**Issue by pokeys369** [splewis/csgo-practice-mode#198]
Hi, i installed practicemode but now i cannoct connect to the server, in log its typing me this, what i have to do? Thank you
L 05/06/2021 - 00:18:30: SourceMod error session started
L 05/06/2021 - 00:18:30: Info (map "de_mirage") (file "errors_20210506.log")
L 05/06/2021 - 00:18:30: [SM] Fatal error encountered parsing translation file "plugin.basecommands.txt"
L 05/06/2021 - 00:18:30: [SM] Error (line 0, column 0): Stream failed to open
L 05/06/2021 - 00:18:30: [SM] Exception reported: Language phrase "Please select a map" not found (arg 5)
L 05/06/2021 - 00:18:30: [SM] Blaming: basecommands.smx
L 05/06/2021 - 00:18:30: [SM] Call stack trace:
L 05/06/2021 - 00:18:30: [SM]   [0] Menu.SetTitle
L 05/06/2021 - 00:18:30: [SM]   [1] Line 87, D:\builds\build-sourcemod-msvc12\windows-1.9\build\plugins\basecommands.sp::OnPluginStart
L 05/06/2021 - 00:18:30: [SM] Unable to load plugin "basecommands.smx": Error detected in plugin startup (see error logs)
L 05/06/2021 - 00:18:31: [SM] Fatal error encountered parsing translation file "nextmap.phrases.txt"
L 05/06/2021 - 00:18:31: [SM] Error (line 0, column 0): Stream failed to open
L 05/06/2021 - 00:18:31: [SM] Fatal error encountered parsing translation file "playercommands.phrases.txt"
L 05/06/2021 - 00:18:31: [SM] Error (line 0, column 0): Stream failed to open
L 05/06/2021 - 00:18:31: [SM] Fatal error encountered parsing translation file "reservedslots.phrases.txt"
L 05/06/2021 - 00:18:31: [SM] Error (line 0, column 0): Stream failed to open
L 05/06/2021 - 00:18:31: [SM] Fatal error encountered parsing translation file "sounds.phrases.txt"
L 05/06/2021 - 00:18:31: [SM] Error (line 0, column 0): Stream failed to open
L 05/06/2021 - 00:18:42: Error log file session closed.
L 05/06/2021 - 00:18:43: SourceMod error session started
L 05/06/2021 - 00:18:43: Info (map "de_mirage") (file "errors_20210506.log")
L 05/06/2021 - 00:18:43: [SM] Fatal error encountered parsing translation file "plugin.basecommands.txt"
L 05/06/2021 - 00:18:43: [SM] Error (line 0, column 0): Stream failed to open
L 05/06/2021 - 00:18:43: [SM] Fatal error encountered parsing translation file "nextmap.phrases.txt"
L 05/06/2021 - 00:18:43: [SM] Error (line 0, column 0): Stream failed to open
L 05/06/2021 - 00:18:43: [SM] Fatal error encountered parsing translation file "playercommands.phrases.txt"
L 05/06/2021 - 00:18:43: [SM] Error (line 0, column 0): Stream failed to open
L 05/06/2021 - 00:18:43: [SM] Fatal error encountered parsing translation file "reservedslots.phrases.txt"
L 05/06/2021 - 00:18:43: [SM] Error (line 0, column 0): Stream failed to open
L 05/06/2021 - 00:18:43: [SM] Fatal error encountered parsing translation file "sounds.phrases.txt"
L 05/06/2021 - 00:18:43: [SM] Error (line 0, column 0): Stream failed to open

**Comment by ramondv** [comment]
Hey, did you fix that?

**Comment by splewis** [comment]
Nothing in this log is related to practicemode, so there's not enough information to help here. It looks like all plugins can't read their translation files though. Might have been a filesystem permissions issue.
