### ISSUE TITLE
Make .setup for admins only

### ISSUE THREAD

**Issue by ngx3** [splewis/csgo-practice-mode#20]
Is there a way to add it for admins only, right now anyone who joins the server can use it. Is there a way so admins with a specific permission can use it?

**Comment by splewis** [comment]
That was definitely an oversight. I just made a change so it is:
- admin restricted by default (g flag)
- but can override to have no admin required via the sourcemod override system

I'll probably make a newer release with this change soonish, but you could download a new build from https://ci.splewis.net/job/csgo-practice-mode/ if you'd like.

**Comment by ngx3** [comment]
Thanks!

**Comment by splewis** [comment]
Closing since this is done.
