### ISSUE TITLE
Add new chat alias' and where to define them

### ISSUE THREAD

**Issue by Sicariusdh** [splewis/csgo-practice-mode#204]
I'm trying to make a chat alias of ".noprac" for "sm_exitpractice" but it seems the chat alias isn't defined, and therefore wont execute "sm_exitpractice". I can't seem to find where the chat alias' are defined. How/Where are they Chat Alias' defined?

**Comment by splewis** [comment]
They're defined within the plugin's code, so they're not easily customizable: https://github.com/splewis/csgo-practice-mode/blob/master/scripting/practicemode.sp#L303-L608


`.noprac` sounds generally useful, so I'd be happy to accept a PR adding it.
