### ISSUE TITLE
Practice mode crash server after Operation Riptide

### ISSUE THREAD

**Issue by LukasW1337** [splewis/csgo-practice-mode#208]
### Expected behavior
Not crashing

### Actual behavior
Server crashes on player connect - Segmentation fault

### Steps to reproduce
- Plugin version: Latest 304 build
- Sourcemod version: 1.10
- Steps to reproduce (please be specific):

Use a clean server with practice mode, metamod and sourcemod. Connect to it - it should crash.

**Comment by CrazyHPi** [comment]
you can remove botmimic.smx as a temporary fix, some other functions are broken rn

**Comment by LukasW1337** [comment]
Looks like you just have to manually update sourcemod to the new build 2 hours ago - then it doesn't crash

**Comment by CrazyHPi** [comment]
still you only get 0/1 nades and it disappear after you throw it / swap to another weapon

**Comment by itzshahay** [comment]
> 
> 
> still you only get 0/1 nades and it disappear after you throw it / swap to another weapon

^this. I can't for the life of me, however figure out how it could be a plugin issue, seems like a cfg issue maybe. But happens to me too

**Comment by possiblyblank** [comment]
> > still you only get 0/1 nades and it disappear after you throw it / swap to another weapon
> 
> ^this. I can't for the life of me, however figure out how it could be a plugin issue, seems like a cfg issue maybe. But happens to me too

I've got the same problem, nades disappear from the list as soon as I select them. I don't have any other cfgs executing. 
Tried running the command manually, still not working.

**Comment by itzshahay** [comment]
> 
> 
> > > still you only get 0/1 nades and it disappear after you throw it / swap to another weapon
> > 
> > 
> > ^this. I can't for the life of me, however figure out how it could be a plugin issue, seems like a cfg issue maybe. But happens to me too
> 
> I've got the same problem, nades disappear from the list as soon as I select them. I don't have any other cfgs executing.
> Tried running the command manually, still not working.

sv_infinite_ammo 2 should temporarily fix this

**Comment by splewis** [comment]
I'll note that the default config file (`addons/sourcemod/practicemode.cfg`) has now been modified, which should prevent this: https://github.com/splewis/csgo-practice-mode/commit/bd1dc5dffd292c14b1a3b2b0b9d3ae9285280cb6 

If you download the 1.3.4 release or later, you will also get this newer config: https://github.com/splewis/csgo-practice-mode/releases
