### ISSUE TITLE
Feature Request: Lock saved replay for editing

### ISSUE THREAD

**Issue by m4Ssa** [splewis/csgo-practice-mode#212]
Loving the .replays feature, but having fat-fingers and accidentially editing/removing a recorded player from a replay is pain. Would be nice if we could lock replays after finishing them so they cannot be edited until unlocked again.

**Comment by splewis** [comment]
Good thought, this should be pretty easy to add. I'll see if I can add it in the next few days.

**Comment by m4Ssa** [comment]
Great thanks!

**Comment by splewis** [comment]
Added a "freeze role data" setting in https://github.com/splewis/csgo-practice-mode/commit/f63837476a34b6b284925eeaac9944ac62358b05

You could get a new version of the plugin at https://ci.splewis.net/job/csgo-practice-mode/309/ (practicemode-309.zip) and use it now if you want.

Let me know if you have any issues or feedback on it.

**Comment by m4Ssa** [comment]
Looking good! Though freezing the replay disables going into the roles and checking the used grenades or just playing a single role. Maybe having these still available while frozen could be a thing?

**Comment by splewis** [comment]
Ah yes, I'll tweak that.

**Comment by splewis** [comment]
Made some tweaks, [build 310](https://ci.splewis.net/job/csgo-practice-mode/310/) should have them.

**Comment by m4Ssa** [comment]
Still can't look at the PoV's once the replay is locked:
![image](https://user-images.githubusercontent.com/30254532/143773651-365c4a39-9308-4a89-a295-cfbfc08069ad.png)

Looking at the changes probably forgot to remove the freezing on the replays main page.

**Comment by splewis** [comment]
Are you sure you're using build 310 or higher?  That was the line 22 change in https://github.com/splewis/csgo-practice-mode/commit/afab77b039b05199e869dcb438c4a191de9f83d1

**Comment by m4Ssa** [comment]
Ye you were right, works perfectly now. Somehow didnt copy the files properly after downloading.
