### ISSUE TITLE
Practice does not work

### ISSUE THREAD

**Issue by IMDOMINIK** [splewis/csgo-practice-mode#213]
Hi, when I run the practice mod via ".setup" it shows me a menu only with the option to turn on or off the training mode and in the chat only the time of the grenade flight, damage ... and I can use all the commands, but it does not kick the bots, time is limited, I can shop only at spawn, etc. Can you please help me?
Than you
Bye
https://snipboard.io/591qBn.jpg

**Comment by splewis** [comment]
You probably didn't copy the addons/sourcemod/configs/practicemode.cfg file
to your server from the download.
