### ISSUE TITLE
Can't figure out how to change prefix

### ISSUE THREAD

**Issue by Kado201** [splewis/csgo-practice-mode#215]
I originally posted this in discussions but felt issues would be more appropriate. Couldn't figure out how to remove my post in discussions so apologies for the double post.

I went into native.sp for the plugin and changed the Define prefix line from Default to my team's name, however nothing changed. I'm not sure if I went to the right place to change the prefix name or if I just did something wrong. If possible I would also like to learn how to change the color of the prefix. Thanks for any help!
Edit: If possible I would also like to know how to change the color of the prefix for the get5 plugin as I've figured out how to change the prefix but not the color

**Comment by splewis** [comment]
You can recompile the plugin to do anything you want; but I don't provide support for arbitrary code edits.
