### ISSUE TITLE
I can't figure out why my server console is flooded with File /home/container/csgo/pak01_170.vpk was never closed everytime I restart

### ISSUE THREAD

**Issue by Kado201** [splewis/csgo-practice-mode#217]
As the title states every time I've restarted my server lately it is absolutely flooded with similar messages to the one in the subject. The server host I have is nodecraft and after asking them about it they basically told me it probably has to do with one of my plugins/addons, but I have zero idea how to figure out which addon would be messing with it. 

The only plugins I have are prac mode, get5 and ws/knife and gloves. I tried googling it but everything I found is pretty outdated and had something to do with people getting kicked from game servers with a similar error, nothing to do with it happening in server console.

Any info would be very much appreciated

**Comment by mrc4tt** [comment]
It would be better if you could give us a screenshot. So we better can help you ;)

**Comment by Kado201** [comment]
https://gyazo.com/94edb845229c4ec342894fc2a02bafd7
Sorry lol, completely forgot to link the screenshot.

**Comment by mrc4tt** [comment]
Do you have GSLT token installed? Maybe the GSLT token are expired (has nothing to-do with the plugin btw)

**Comment by Kado201** [comment]
Yes, my server and all the plugins are running with zero problems, just not sure why my console is being flooded with those lines out of the blue. I figured it probably didn't have anything to do with this specific plugin I just wasn't sure where else to post this

**Comment by mrc4tt** [comment]
You can ask at the alliedmodders forum =)

I think your problem can only be "GSLT token" because it shows "that" e.g. if server shutdown/restart - if you have autoupdate enabled e.g.

**Comment by Kado201** [comment]
Ohhh okay that makes sense, Ill ask there. Thanks for the info!
