### ISSUE TITLE
Time for nade tails to last

### ISSUE THREAD

**Issue by iceman20k** [splewis/csgo-practice-mode#22]
Hi splewis, one more good job here!
Can you please add a convar to adjust the time the nade tails will stay like in this plugin: https://forums.alliedmods.net/showthread.php?t=240668

When finding some tricky smokes it helps to screenshot the line etc.

Thanks!

**Comment by splewis** [comment]
You can set sv_grenade_trajectory_time.

**Comment by iceman20k** [comment]
Thanks for your answer. True, but it seems like it is limited to max 20. A value of 40 would be better for sme needs.

**Comment by splewis** [comment]
The cvar is built into the game, so only I can't change its max, only valve can.

**Comment by iceman20k** [comment]
Well ok, thanks again. Just wonder why the plgin metioned above can...

**Comment by splewis** [comment]
Because it has its own cvar instead of reusing existing cvars like this plugin does. I don't think it's worth the confusing of having duplicate cvars to change their default/mins/maxes.

**Comment by iceman20k** [comment]
Ahh ok, i see. Sounds like a concept, yes ;) Still you might be thinking about it. I have a tarining group with about 20 ppl, all of them found that useful when finding tricky smokes that have to be thrown very exactly. But of course dont wanna break your concept. This might be a border case, though.
