### ISSUE TITLE
Practice does not work

### ISSUE THREAD

**Issue by IMDOMINIK** [splewis/csgo-practice-mode#229]
### Expected behavior
Practice mod will work

### Actual behavior
When I write ".prac" or ".setup" to the chat, nothing will happen. I reinstalled the whole server, installed the plugin according to the instructions and it still doesn't work. 

### Steps to reproduce
- Plugin version: 1.3.4
- Sourcemod version: 1.10.0
- Metamod version: 1.10.7
- Steps to reproduce (please be specific):
  Can you help me how to fix it please?
Thank you 
Bye

**Comment by GenocideStomper** [comment]
I have the same issue now. It used to work, for about a week now it doesn't. I don't know how to diagnose the issue or where to look for logs.

**Comment by GenocideStomper** [comment]
Ok, issue was an upgrade from Ubuntu 20.04 to 22.04.

These commands fixed it for me, not sure which ones are actually required (I'm using LGSM):
`sudo apt install libc6:i386 lsb-core`
`sudo apt install lib32z1`
`sudo apt install ia32-libs`
`sudo apt install build-essential`
`rm serverfiles/bin/libgcc_s.so.1`
`sudo reboot`

**Comment by splewis** [comment]
I'm sorry, but issues like this aren't something I can help with. You need to get more information (is sourcemod running? is the plugin loaded? did you check for plugin error logs?) for anyone to be able to help.

If you still need help, the support discord (https://discord.gg/zmqEa4keCk) might be a better place to ask.
