### ISSUE TITLE
.flash breaks when grenade-trajectories are disabled

### ISSUE THREAD

**Issue by atrefz** [splewis/csgo-practice-mode#23]
### Expected behavior
Even with turned off grenade trajectories, .flash should teleport me to the position I saved and then back to the position i threw the grenade from.

### Actual behavior
When the trajectories are turned of, I only get teleported back to the place a threw the grenade from, but not the .flash position.

### Steps to reproduce
- Plugin version: 1.1.2
- Sourcemod version: 1.8
- Turn on Practice Mode
- Turn off grenade trajectories
- .flash somewhere
- move somewhere else and throw a flash

**Comment by splewis** [comment]
Thanks for the great bug report! This is fixed now.

**Comment by atrefz** [comment]
Thanks for the quick fix!
