### ISSUE TITLE
Unable to use PM_OnGrenadeSaved 

### ISSUE THREAD

**Issue by Sh3nl0ng** [splewis/csgo-practice-mode#235]
Should this be forwarding `PM_OnGrenadeSaved` instead of `PM_OnPracticeModeEnabled`?

https://github.com/splewis/csgo-practice-mode/blob/3c6b3e5096c4b7b7bfeb570284d328cd2fbcb888/scripting/practicemode.sp#L270-L271

**Comment by splewis** [comment]
Yup, that's exactly the bug. Feel free to send a pull request, though I'll try to fix it tonight.

**Comment by Sh3nl0ng** [comment]
https://github.com/splewis/csgo-practice-mode/pull/236

**Comment by Sh3nl0ng** [comment]
merged
