### ISSUE TITLE
.fastforward doesn't actually speed up smoke dissipation

### ISSUE THREAD

**Issue by Technoblazed** [splewis/csgo-practice-mode#24]
### Expected behavior

The .fastforward command speeds up the server and the smoke disappears.

### Actual behavior

The .fastforward command speeds up the server, but doesn't actually change the speed the smoke dissipates.

### Notes

Could this have something to do with changing it from `ServerCommand` to the `SetCvar`?

**Comment by splewis** [comment]
It works just fine for me at 35eefbbc530281d7dc75b60cb3c643da7ac87717.

**Comment by kAlekki** [comment]
The fastforward command seems to work only sometimes, other times it does fast forward the time, but the particles still stay on the client.

**Comment by bykidi** [comment]
A video on that would be cool to see

**Comment by bykidi** [comment]
Tested it on last release & snapshot - everything is fine.

**Comment by necuk** [comment]
for not being able to provide any better feedback, but still — I noticed that .ff didnt work for the smokes for some time while I was on the server. I randomly tried in 2-3 minutes and it worked. So the time was speed up but smokes didnt disappear for some reason

**Comment by Technoblazed** [comment]
Yeah I'm noticing it working every now and again, but it's not completely consistent.

**Comment by splewis** [comment]
I slowed down the host_timescale to set it to 10 instead of 20. Maybe it helps with this, but I've still never been able to reproduce it - so I'm closing this.
