### ISSUE TITLE
Plugin not working offline anymore

### ISSUE THREAD

**Issue by OLDMIKE38** [splewis/csgo-practice-mode#255]
I've used this plugin to practice my nades OFFLINE, so without a dedicated server. This used to work fine, i would add the command -insecure to my launch options and just load up a map and type .prac to start the mod. But now it seems like i cant get it working and i can't figure out why. I haven't changed anything. 

Any help would be greatly appreciated!

**Comment by splewis** [comment]
Sourcemod isn't supported on non-dedicated servers (https://forums.alliedmods.net/showthread.php?t=305122), so you're really on your own trying to get it to work. Sorry for the bad news.
