### ISSUE TITLE
You cannot use .setup right now.

### ISSUE THREAD

**Issue by jonatangrim** [splewis/csgo-practice-mode#26]
When typing .setup, server responds with:
[PracticeMode] You cannot use .setup right now.

When can I use .setup?
What am I missing?

**Comment by bykidi** [comment]
Add youself to admins.ini in sourcemod config folder. Try sm_admin in console. After that try the .setup command.

**Comment by jonatangrim** [comment]
Okay, it's "working" now.

Infinity ammo does not work.
What is wrong with this?

Am I missing a global configuration to make this work?
Do I need to put something in my server.cfg?

**Comment by bykidi** [comment]
Nope, you don't need anything. I think...
In the .setup menu you can enable the infinite ammo (with reload)

**Comment by splewis** [comment]
Infinite ammo probably works, but you expected it to set sv_infinite_ammo to 1 instead of 2. You can change that in the practicemode config: https://github.com/splewis/csgo-practice-mode/blob/master/configs/practicemode.cfg#L62

**Comment by splewis** [comment]
Closing since I don't see any bugs here. Feel free to reopen if you think that's not the case.
