### ISSUE TITLE
Can't enable sv_cheats and godmode all of a sudden

### ISSUE THREAD

**Issue by Swendo** [splewis/csgo-practice-mode#27]
Just in the last few weeks typing god in console and sv_cheats no longer work. I also have to say .noclip instead of just a console bind.

**Comment by splewis** [comment]
Setting sv_allow_legacy_cmd_execution_from_client  might help.

Are you sure sv_cheats actually isn't set, or that it just seems to have to effect? Can you check the actual value of sv_cheats in console.

**Comment by bykidi** [comment]
Hey, i got the same problem. Though my practicemode installation was broken.

**Comment by bykidi** [comment]
![20170509154912_1](https://cloud.githubusercontent.com/assets/1337953/25851610/19ad37c4-34cf-11e7-9006-a5b7b9816d86.jpg)
![20170509154914_1](https://cloud.githubusercontent.com/assets/1337953/25851611/19b2ebb0-34cf-11e7-8355-eea89dace734.jpg)

**Comment by Swendo** [comment]
sv_allow_legacy_cmd_execution_from_client solved the issue thanks

**Comment by splewis** [comment]
As far as I can tell like this is unrelated to practicemode. I'll consider adding sv_allow_legacy_cmd_execution_from_client  to the default config alongside the sv_cheats setting.
