### ISSUE TITLE
Suddenly "noclip" stopped working

### ISSUE THREAD

**Issue by iceman20k** [splewis/csgo-practice-mode#28]
Hey there,

on my server "noclip" suddenly stopped working. Checked .setup, its enabled, updated SM and Metamod to latest version. Just wanted to ask if someone also encounters this or if its actually a problem with my setup. Thanks for any hints.

**Comment by bykidi** [comment]
#27

**Comment by iceman20k** [comment]
Hey,

sorry, just in that sec i found it myself, temp fix is:

sv_allow_legacy_cmd_execution_from_client 1

for anyone just coming over the page again and thus may make the dumb question any helpful.
