### ISSUE TITLE
bot commands not working

### ISSUE THREAD

**Issue by Swendo** [splewis/csgo-practice-mode#29]
None of the bot commands seem to be working

**Comment by splewis** [comment]
The template when you create an issue exists for a reason. Without version numbers, it's extremely difficult to help people.

None of the bot commands have made it into a release version yet. That's why they're probably not on your server.

**Comment by Swendo** [comment]
Sorry for that I was on mobile and had some troubles. Thanks for the fast reply



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
