### ISSUE TITLE
[PracticeMode] You cannot use .setup right now.

### ISSUE THREAD

**Issue by gevoxBLAOW** [splewis/csgo-practice-mode#33]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

.setup should open the menu..idk if searched for hours a solution.. :/

### Actual behavior
->
[PracticeMode] You cannot use .setup right now.

### Steps to reproduce
- Plugin version:
- Sourcemod version:

**Comment by bykidi** [comment]
You are not admin.
#26

**Comment by splewis** [comment]
https://github.com/splewis/csgo-practice-mode/blob/master/README.md#installation

**Comment by splewis** [comment]
Closing since there's no bug. Feel free to reopen if you have any issues.
