### ISSUE TITLE
Remove player names

### ISSUE THREAD

**Issue by acrylicus** [splewis/csgo-practice-mode#35]
Hi Splewis,

I use your pluigins for retakes and my pracc server! I love it and would like to donate.

However, there is 1 request I have... would you be able to guide me on how to remove the names of the person that made the grenade on this plugin?

I edited the SP files to get rid of ownerName and ownerAuth but it did not work!

Again please provide donation links, you've really earned it!

Cheers,
Josh

**Comment by splewis** [comment]
I don't know what you mean by "remove player names". I am assuming you mean something like https://github.com/splewis/csgo-practice-mode/issues/31, which is something I'm working on. The idea being that anyone can edit anybody else's grenades, and the "owner" is never displayed and doesn't matter. (The data file is the same format, and each nade has an owner, it just doesn't matter and is invisible when you're in the server)

**Comment by acrylicus** [comment]
When I do .cats to browse our library of bases, it has a format of below:

(1-7) <name of nade> (<person who made it>-id)

I'd like it to just be (1-7) <name of nade>

**Comment by splewis** [comment]
That's a change I'm not planning to make (of course you are free to edit the plugin, but I can't help with people wanting to make arbitrary code changes).

The change part of https://github.com/splewis/csgo-practice-mode/issues/31 would give you a way to not show the user, but the id number will still be there.

**Comment by splewis** [comment]
The ``sm_practicemode_share_all_nades`` cvar is added now, which kind of helps with your request. 

If you fully want to remove the name, you'd have to edit at https://github.com/splewis/csgo-practice-mode/blob/master/scripting/practicemode/grenademenus.sp#L300 and recompile.

I still don't think it's worth adding a cvar for this, so I'm closing the issue.
