### ISSUE TITLE
.back and .last not working

### ISSUE THREAD

**Issue by ViciousDREW** [splewis/csgo-practice-mode#37]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
When users type .back or .last into chat they will return to previous nade position.

### Actual behavior
Nothing happens when commands .back and .last are entered into chat. 

### Steps to reproduce
- Plugin version:1.1.3
- Sourcemod version:1.8

**Comment by splewis** [comment]
Thanks, should be fixed now.

I'll likely put out a new release tomorrow so the fix is included.
