### ISSUE TITLE
Add alternative to .setup when csgo-pug-setup is installed

### ISSUE THREAD

**Issue by SM411** [splewis/csgo-practice-mode#4]
Hi!
I run a server used for both pugs and pratice. Could there be an alternative way to start pratice, like .pratice so both addons can run at the same time?

**Comment by splewis** [comment]
I don't know what you mean by "run at the same time", but there is a sm_practice command that launches practice mode (e.g. by typing !practice in chat).

**Comment by SM411** [comment]
Thanks. This solves my problem. I did not know the alternative ways to start practice mod, and when pugsetup was enabled, .setup did start pugsetup.
