### ISSUE TITLE
.back and other not working

### ISSUE THREAD

**Issue by Minoo7** [splewis/csgo-practice-mode#40]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
.back would go back to where i threw my nade 

### Actual behavior

.back to go back to nade is not working =nothing happens
### Steps to reproduce
- Plugin version:
- Sourcemod version:

**Comment by bykidi** [comment]
https://github.com/splewis/csgo-practice-mode/issues/37

**Comment by splewis** [comment]
Already fixed. Please provide version numbers in the future, it's requested for a reason.
