### ISSUE TITLE
"Nade-Bot" stays connected after Ending Practicemode

### ISSUE THREAD

**Issue by JackJack3231** [splewis/csgo-practice-mode#41]
### Expected behavior
When exiting Practicemode the invisible "Nade-Bot" should get kicked from the server (like all bots)

### Actual behavior
Invisible "Nade-Bot" stays connected

### Steps to reproduce
- Plugin version: 1.2.0-dev+131
- Sourcemod version: 1.8.0.6027

Start Practicemode
Throw Grenade
Use .throw / sm_throw
Exit Practicemode
Use "status" command in console

**Comment by splewis** [comment]
Good catch. Should be fixed now.
