### ISSUE TITLE
Black Screen probably caused from Spectating invisible Nade-Bot

### ISSUE THREAD

**Issue by JackJack3231** [splewis/csgo-practice-mode#42]
### Expected behavior
You should never be able to spectate the invisible Nade-Bot

### Actual behavior
When you join the Spectators, if there is no Player or Bot that joined before the Nade Bot u get stuck with a black screen.
If the Player you spectate leaves (disconnects or joins Spectators) and there is no Player left that you could spectate you also get stuck with a black screen.

NOTE: Spectating Priority sometimes seems to favor Players you just spectated over when they joined, so if you just spectated a Player (Client # 3) that joined after the Nade Bot ("Client" # 2) then switched to a Player (Client # 1) that joined before the Nade Bot and he leaves (Client # 1) it could happen that you are switched over to Client # 3 and don't get stuck with a black screen.

### Steps to reproduce
- Plugin version: 1.2.0-dev+138
- Sourcemod version: 1.8.0.6027

NOTE: In this Procedure the bots are representing Players that join the game, it should work exactly the same with Players that join the game.

Launch Practicemode
Place a bot
Throw a grenade and use .throw
Place some more bots
Join spectators
Spectate first bot from firstperson
Kick the first bot

You should be stuck with a black screen now and seem not to be able to change Spectating Target

**Comment by splewis** [comment]
I tried to reproduce this, if there's other alive players using number keys works fine. I'm not sure if this is worth fixing.

**Comment by Joele25** [comment]
What do you mean by "other alive players using number keys"? I've got the same problem

**Comment by JackJack3231** [comment]
Now that csutils doesn't use a Bot anymore this probably can be closed.
