### ISSUE TITLE
Spawn points are incorrect

### ISSUE THREAD

**Issue by gg** [splewis/csgo-practice-mode#47]
### Expected behavior

*All* 5v5 competitive spawn points, and *only* 5v5 competitive spawn points should be considered when using the `.spawn`, `.bestspawn`, and `.worstspawn` commands.

### Actual behavior

- Some 5v5 competitive spawn points are not available when using `.spawn`, `.bestspawn`, `.worstspawn`.
- Additional non-competitive spawn points are available(e.g. Wingman mode).

### Steps to reproduce
- Plugin version: 1.2.0
- Sourcemod version:  1.8.0.6015
- Start a local listen server with 4 bots on your team.
- Type `map_showspawnpoints` in console to see which spawn points are available.
- Restart the round several times to see where you and the bots spawn.
- Join a server with the practice mode plugin enabled and cycle through spawn points via `.spawn` and notice that not all competitive spawn points are used and/or *additional* non-competitive spawn points are used.

#### de_cbble CT

**15 expected de_cbble competitive CT 5v5 spawn points (using `map_showspawnpoints`)**
![cbble competitive CT spawns using map_showspawnpoints](https://i.imgur.com/tThIYAx.jpg)

**Only *9* de_cbble CT spawn points are considered (4 of which are Wingman mode spawn points)**:
- **.spawn 1 (of 9)** ![.spawn 1 (of 9)](https://i.imgur.com/PwBjGVI.jpg)
- **.spawn 2 (of 9)**  ![.spawn 2 (of 9)](https://i.imgur.com/Hmn9zEW.jpg)
- **.spawn 3 (of 9)**  ![.spawn 3 (of 9)](https://i.imgur.com/DysXzyS.jpg)
- **.spawn 4 (of 9)**  ![.spawn 4 (of 9)](https://i.imgur.com/vLwYsox.jpg)
- **.spawn 5 (of 9)**  ![.spawn 5 (of 9)](https://i.imgur.com/w65T6jx.jpg)
- **.spawn 6 (of 9) [Wingman]**  ![.spawn 6 (of 9)](https://i.imgur.com/JDBYeIM.jpg)
- **.spawn 7 (of 9) [Wingman]**  ![.spawn 7 (of 9)](https://i.imgur.com/ZPQuAni.jpg)
- **.spawn 8 (of 9) [Wingman]**  ![.spawn 8 (of 9)](https://i.imgur.com/INEcaaA.jpg)
- **.spawn 9 (of 9) [Wingman]**  ![.spawn 9 (of 9)](https://i.imgur.com/TqXo4Rm.jpg)

#### de_train CT

- **de_train CT: expected best spawn to Z** ![de_train CT expected best spawn to Z](https://i.imgur.com/7tP3xqE.jpg)
- **de_train CT actual .bestspawn to Z** ![de_train CT .bestspawn to Z is wrong](https://i.imgur.com/rd3WxYR.jpg)

#### de_train T

12 expected spawn points, but only 7 spawn points are available via the plugin.

**Comment by splewis** [comment]
The addition of the wingman spawns is a bug (hopefully there's a property on them I can find to differentiate them), but the first image you show is misleading.

The spots on the left (on the A site itself) aren't included in the practicemode command since they're lower priority (based on their ``m_iPriority`` value) spawns that shouldn't be given in 5v5's. There is a bug (which happens on all servers, as far as I know) where the pistol rounds (or maybe just the 1st pistol) causes players to get any of the spawns - including those A site ones - but I don't think it's correct to include those in practicemode still.

**Comment by gg** [comment]
Ah, I didn't know about the first round spawn bug. Thanks for educating me. I agree that it's not correct to include these additional spawns in practicemode.

> edit: checked the sdk, there is an "enabled" field on info_player_counterterrorist at least, so presumably that's what wingman is setting on the new spawns.

That's good to hear.

Thanks for creating this plugin -- my friends and I really appreciate it!

**Comment by splewis** [comment]
Confirmed that https://github.com/splewis/csgo-practice-mode/commit/b8071d16704fcff9f171b3ca1c79c03d69103bee fixed this.
