### ISSUE TITLE
After being teleported to .flash spot I'm not teleported back to the place where the flash was thrown from

### ISSUE THREAD

**Issue by mfjeldheim** [splewis/csgo-practice-mode#49]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
When using .flash and moving to a spot where the flash is thrown from, I am teleported to the point where I typed in .flash after throwing the flash, then I'm teleported back to the place where I threw the flash after the flash ends.

### Actual behavior
As of now on my server I am being teleported to the .flash spot after throwing the flash, I am however not being teleported back to the spot where I threw the flash. What happens now is that I'm stuck in the spot where I typed .flash and I am unable to move in any direction (including jump etc). Only way to get unstuck is to either type "kill" in console or use .noclip

### Steps to reproduce
1. Type .flash
2. Move to a new spot where the flash will be thrown from
3. Get teleported back to the .flash spot
4. Stuck in this position without any possibility of moving from it.

- Plugin version: 1.1.3
- Sourcemod version: 1.8.0.6001

**Comment by splewis** [comment]
Sounds like the same issue that caused https://github.com/splewis/csgo-practice-mode/issues/37

Updating your plugin should fix it.

**Comment by splewis** [comment]
Closing since I think this is resolved.
