### ISSUE TITLE
logs errors

### ISSUE THREAD

**Issue by krispx** [splewis/csgo-practice-mode#5]
hi, jus this logs from last dev verion:

L 02/25/2016 - 20:03:07: SourceMod error session started
L 02/25/2016 - 20:03:07: Info (map "de_dust2") (file "errors_20160225.log")
L 02/25/2016 - 20:03:07: [SM] Fatal error encountered parsing translation file "pugsetup.phrases.txt"
L 02/25/2016 - 20:03:07: [SM] Error (line 0, column 0): Stream failed to open

**Comment by splewis** [comment]
This should be fixed now.
