### ISSUE TITLE
.dryrun not executing

### ISSUE THREAD

**Issue by edvaldatli** [splewis/csgo-practice-mode#54]
### Expected behavior
.dryrun should disable practicemode settings, restart the round, and changes freezetime.

### Actual behavior
The command does not execute after typing .dryrun

### Steps to reproduce
- Plugin version: 1.2.1
- Sourcemod version: 1.8.0.6022

**Comment by splewis** [comment]
That command isn't in 1.2.1. If you type .help ingame, that's the matching documentation for your version: .dryrun shouldn't be there.
