### ISSUE TITLE
Enhancements to trajectories

### ISSUE THREAD

**Issue by baerus** [splewis/csgo-practice-mode#57]
I don't know, if this is actually technically possible/feasable. I got two issues I like to get enhanced if possible, regarding the nade trajectories:

1) **line calculations more precise**
The lines are not as precise calculated as the "real" ones. See here:
https://youtu.be/adB7gEB7qro

2) **visible through walls**
Would be awesome, to see the lines through walls and objects. Would help for example on the following situation. I want to understand where I can go without being flashbanged, and where I should not go. It would be much easier, if I could see the entire line, through the box, to do that:
https://youtu.be/oc5H8ApV-9o

**Comment by splewis** [comment]
As far as I know both of those aren't feasible for the plugin to fix. Valve making the cvar work more generally is the best hope still.
