### ISSUE TITLE
.noflash and .dryrun not working

### ISSUE THREAD

**Issue by Husqiy** [splewis/csgo-practice-mode#58]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
When .noflash is inputted, I expect to not be flashed by a flashbang (while it effecting others and bots).
When .dryrun is inputted, I expect the dryrun exec to start.

### Actual behavior
When .noflash and .dryrun is inputted, nothing happens.

### Steps to reproduce
- Plugin version: 1.2.1
- Sourcemod version: 1.8.0

### Extra
Was this removed or just a bug? If so, why?
Thanks!

**Comment by splewis** [comment]
It works for me.

Can you check for any error logs in ``addons/sourcemod/logs`` and verify the plugin version by typing ``sm plugins`` in console?

**Comment by Husqiy** [comment]
"Check for any error logs"
I'm assuming there isn't any as I don't even have a directory called logs in the sourcemod folder. Here is a Gyazo image to show:
https://gyazo.com/3bce1cba832244e8b55ad08615f00da4

"Verify the plugin version by typing sm plugins"
Nope, the versions I stated are the same and the commands still do not work. Here is a YouTube video to show:
https://www.youtube.com/watch?v=XzW4SVqKWYI

**Comment by splewis** [comment]
It still works for me. I'd suggest reinstalling. I vaguely recall accidentally uploading a wrong release version for some plugin, and having to update it quickly... it may have been this one. 

I guess I should either automate the github release uploading or make an entirely new version next time.. ugh. Sorry.
