### ISSUE TITLE
Practice Mode can't be restarted

### ISSUE THREAD

**Issue by MichalLauer** [splewis/csgo-practice-mode#59]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
When turning off/on Practice mode, it should turn it on/off
### Actual behavior
Nothing happens, console shows:
exec: couldn't exec sourcemod/practicemode_end.cfg
exec: couldn't exec sourcemod/practicemode_start.cfg
### Steps to reproduce
Turn Practice Mode on, then off and its broken
- Plugin version: 1.2.2-dev+166
- Sourcemod version:  1.8.0-git5985

**Comment by splewis** [comment]
I don't really understand what the issue you saw was ("its broken"?), but c1f4d31fab91a9270712b7d826d35ea3023a45eb possibility fixed all the settings being disabled on a practicemode restart.
