### ISSUE TITLE
adding .warmup

### ISSUE THREAD

**Issue by B4LSTAD** [splewis/csgo-practice-mode#61]
Hello. I am managing a pracc-server and i installed Practicemode yesterday.
Its working fine, but the players wants a feature that they have seen on another server earlier.

It basically executes configs, such as warmup.cfg if any client writes .warmup in the ingame chat (not using rcon). Is this a feature that exists in Practicemode, or does it need extra code to work?

**Comment by splewis** [comment]
That's not practicemode feature, ``.prac`` and ``.setup`` are the only ways to start practicemode unless you're using other plugins.

**Comment by B4LSTAD** [comment]
Ok, so i need another plugin then. Anyone u can recommend that would have such a feature?

**Comment by splewis** [comment]
Nope. Asking at https://forums.alliedmods.net/forumdisplay.php?f=60 is likely your best option.
