### ISSUE TITLE
Jump Throw nades not flying proberly

### ISSUE THREAD

**Issue by xMetro** [splewis/csgo-practice-mode#63]
When i jump throw nades it dosent fly proberly so some nades dont work.

but after executing the esl5on5 config. it does get fixed so think the problem maybe in the practicemode config. 

im not 110% sure if its my server config or it is the practice mode config. 
but would be nice id you could look into it.

regards Mathias "Metro"

**Comment by splewis** [comment]
Everything works normally for me. You didn't really give me anything to look into. 

Can you post:
- any sourcemod error logs you have (they're in ``addons/sourcemod/logs``)
- the list of plugins you're using (``sm plugins`` in console)

**Comment by xMetro** [comment]
**My plugin list:**
] rcon sm plugins list
[SM] Listing 20 plugins:
  01 "Fun Commands" (1.8.0.6041) by AlliedModders LLC
  02 "Sound Commands" (1.8.0.6041) by AlliedModders LLC
  03 "csutils" (1.2.2) by splewis
  04 "Player Commands" (1.8.0.6041) by AlliedModders LLC
  05 "Admin File Reader" (1.8.0.6041) by AlliedModders LLC
  06 "Reserved Slots" (1.8.0.6041) by AlliedModders LLC
  07 "Admin Menu" (1.8.0.6041) by AlliedModders LLC
  08 "Basic Commands" (1.8.0.6041) by AlliedModders LLC
  09 "Admin Help" (1.8.0.6041) by AlliedModders LLC
  10 "CS:GO PracticeMode" (1.2.2) by splewis
  11 "Basic Votes" (1.8.0.6041) by AlliedModders LLC
  12 "Fun Votes" (1.8.0.6041) by AlliedModders LLC
  13 "Basic Info Triggers" (1.8.0.6041) by AlliedModders LLC
  14 "Nextmap" (1.8.0.6041) by AlliedModders LLC
  15 "Client Preferences" (1.8.0.6041) by AlliedModders LLC
  16 "Basic Ban Commands" (1.8.0.6041) by AlliedModders LLC
  17 "CS:GO PugSetup" (2.0.4) by splewis
  18 "Basic Chat" (1.8.0.6041) by AlliedModders LLC
  19 "Basic Comm Control" (1.8.0.6041) by AlliedModders LLC
  20 "Anti-Flood" (1.8.0.6041) by AlliedModders LLC
L 02/27/2018 - 08:44:14: rcon from "185.22.75.1:19098": command "sm plugins list"

Dont have any error logs this is the only thing i have
L 02/27/2018 - 08:32:38: SourceMod log file session started (file "L20180227.log") (Version "1.8.0.6041")
L 02/27/2018 - 08:32:38: -------- Mapchange to de_inferno --------
L 02/27/2018 - 08:33:50: -------- Mapchange to de_mirage --------

**Comment by xMetro** [comment]
**I have found the issue**

When you start the practice mode
its sets the to sv_friction 4

but inb csgo it should be sv_friction 5.2

the esl config have it thats why it gets fixed when i exec the esl config.

**Comment by splewis** [comment]
> When you start the practice mode
its sets the to sv_friction 4

It doesn't by default, so I guess you added it in?

**Comment by xMetro** [comment]
My bad. missed in my server.cfg
