### ISSUE TITLE
csutils bot can't throw nades (.throw is broken)

### ISSUE THREAD

**Issue by splewis** [splewis/csgo-practice-mode#64]
I suspect something needs to change at: https://github.com/splewis/csgo-practice-mode/blob/f6950fd545e540959169e74268120b72b258f130/scripting/csutils.sp#L210

Some (very) brief testing shows the technique can still work, but the timing of commands may need to change. For example: I had some success forcing myself (a human client on the server) to throw a nade if I delayed more between giving a smoke and the IN_ATTACK forcing. 

(This breaks .throw in practicemode and auto-nade throwing in executes)

**Comment by LKAY91** [comment]
.throw command is complelty wrecked. nothing works anymore. i can still save nades, but .throw doesnt allow me to throw any nades!

**Comment by migael2011** [comment]
Is it possible to get an ETA on how long the fix will take ?

**Comment by m4rkey** [comment]
I don't mean to be disrespectful to you two, but this issue wasnt created for you to spew the already obvious that this plugin is broken, it provided constructive information to developers like myself on this issue and maybe we can collaborate to find a fix.

Give splewis time, Im sure he wants to fix it just as much as you do.

**Comment by splewis** [comment]
Update: I'm hopeful I'll have a fix out tomorrow that changes csutils to not need bots at all.

**Comment by splewis** [comment]
I just pushed a change to the csutils plugin which should fix this. Note that it's not fully backwards compatible, so users will need to update client plugins of it (the CSU_OnGrenadeThrown forward has added an entity arg).

To test this update, you should download from https://ci.splewis.net/job/csgo-practice-mode/lastSuccessfulBuild/ and update both practicemode.smx and csutils.smx.

I'll post an update on the executes issues what execute users should do.

**Comment by m4rkey** [comment]
@splewis It seems to have fixed the nade throwing issue and the smokes bloom however no sounds are being played. Any ideas on that?

**Comment by splewis** [comment]
Try a newer version that includes 3849e4e339397e7421428a0e0385bba1126e3be9.

**Comment by m4rkey** [comment]
I just cloned and compiled it, @splewis No dice. 

Double checked to make sure.

**Comment by m4rkey** [comment]
@splewis I did some testing, and no flashbangs were being thrown in Executes, is it related to csgo-practice-mode or is it a seperate issue all together? Have you had this same issue?

**Comment by splewis** [comment]
I have seen no issues with flashes. If you can reproduce a bug in practicemode, feel free to open a new issue. I'm not going to look into any executes issues until I'm confident in practicemode working.

The only issue I have now with csutils grenades is a crash on collision, which I'll move over to https://github.com/splewis/csgo-practice-mode/issues/68

**Comment by splewis** [comment]
9692747d1f9e99e91c56b7d1df37c98e3d739f25 has fixed the obvious csutils problems.

I'm closing this since I'm not aware of any current issues (though some probably exist).
