### ISSUE TITLE
Bots are not respawning anymore (after their death)

### ISSUE THREAD

**Issue by SchwaByyjee** [splewis/csgo-practice-mode#65]
When i place a bot (with .bot) the bot is actually not respawning anymore.
I think it was an update that changed it.
In my point of view it makes more sense to respawn the bot again after his death than not respawning him.
You can place bots for a prefire-practice quite easily and aswell checking up molotovs etc.

Really nice plugin and aswell the new execute-plugin is a great idea ;D

Best regards
SchwaB

**Comment by GabeHirakawa** [comment]
splewis is already aware of this
see this: #64

**Comment by splewis** [comment]
No, this is unrelated to that bug. I think the csgo update Thursday broke it.

I've noticed the bots respawn, but it takes way longer (like 45+ seconds).

**Comment by splewis** [comment]
a9cd0373e584d2969855e906c00825b64fc375b0 has hopefully fixed this.

You can test it by downloading a build from https://ci.splewis.net/job/csgo-practice-mode/lastSuccessfulBuild/ and replacing the files in addons/sourcemod/plugins (csutils.smx and practicemod.smx).
