### ISSUE TITLE
Explosions of HE Grenades thrown with .throw does no damage

### ISSUE THREAD

**Issue by JackJack3231** [splewis/csgo-practice-mode#70]
### Expected behavior
HE Explosions should do AoE damage

### Actual behavior
Explosions of HEs thrown with .throw does no damage

### Steps to reproduce
Place Bot
Throw HE next to bot
.throw

- Plugin version: 1.2.3-dev+193
- Sourcemod version: 1.8.0.6041

**Comment by splewis** [comment]
9692747d1f9e99e91c56b7d1df37c98e3d739f25 should have this fixed.
