### ISSUE TITLE
Grenades doesen't seem to save

### ISSUE THREAD

**Issue by mhmSure** [splewis/csgo-practice-mode#73]
### Expected behavior

Grenades that has been saved to still be there after restart / map change

### Actual behavior

They are all removed

### Steps to reproduce
- Plugin version: 1.2.2
- Sourcemod version: 1.8(.0)

**Comment by mhmSure** [comment]
`L 03/02/2018 - 16:18:01: SourceMod error session started
L 03/02/2018 - 16:18:01: Info (map "de_mirage") (file "errors_20180302.log")
L 03/02/2018 - 16:18:01: [SM] Exception reported: Not enough space on the heap
L 03/02/2018 - 16:18:27: Error log file session closed.
L 03/02/2018 - 16:18:27: SourceMod error session started
L 03/02/2018 - 16:18:27: Info (map "de_mirage") (file "errors_20180302.log")
L 03/02/2018 - 16:18:27: [SM] Exception reported: Not enough space on the heap


----


L 03/09/2018 - 16:35:06: SourceMod error session started
L 03/09/2018 - 16:35:06: Info (map "de_mirage") (file "errors_20180309.log")
L 03/09/2018 - 16:35:06: [SM] Exception reported: Not enough space on the heap
L 03/09/2018 - 17:08:09: SourceMod error session started
L 03/09/2018 - 17:08:09: Info (map "de_mirage") (file "errors_20180309.log")
L 03/09/2018 - 17:08:09: [admin-flatfile.smx] Error(s) detected parsing addons\sourcemod\configs\admins_simple.ini
L 03/09/2018 - 17:08:09: [admin-flatfile.smx]  (line 65) Could not open file!
L 03/09/2018 - 17:08:39: [admin-flatfile.smx] Error(s) detected parsing addons\sourcemod\configs\admins_simple.ini
L 03/09/2018 - 17:08:39: [admin-flatfile.smx]  (line 65) Could not open file!
L 03/09/2018 - 17:10:07: Error log file session closed.
`

Not sure if any of this is related

**Comment by splewis** [comment]
I'd update sourcemod and try to resolve and errors you're getting in error logs.

**Comment by mhmSure** [comment]
@splewis Sourcemod is the newest all the errors is fixed il check if it still doesent save Grenades
