### ISSUE TITLE
Practice mode cannot be launched or exited via RCON

### ISSUE THREAD

**Issue by cycloidsoftware** [splewis/csgo-practice-mode#74]
### Expected behavior
`sm_prac` and its aliases launch practice mode when executed via `rcon` or `sm_rcon`.

### Actual behavior
Nothing happens.

### Steps to reproduce
- Plugin version: 1.2.2
- Sourcemod version: 1.8.0.6024

**Comment by splewis** [comment]
```
Mar 11 00:13:09:  sm_prac
Mar 11 00:13:09:  Tried to look up command mp_warmup_end as if it were a variable.
Mar 11 00:13:09:  Tried to look up command bot_kick as if it were a variable.
Mar 11 00:13:09:  [#005PracticeMode#001] Practice mode is now enabled.
Mar 11 00:13:09:  exec: couldn't exec sourcemod/practicemode_start.cfg
Mar 11 00:14:21:  sm_exitpractice
Mar 11 00:14:21:  [#005PracticeMode#001] Practice mode is now disabled.
```

I can't reproduce this. Can you launch it normally, in game?

**Comment by cycloidsoftware** [comment]
In game, if I run `sm_prac` it works, however `rcon sm_prac` or `sm_rcon sm_prac` do not.

**Comment by splewis** [comment]
I still can't reproduce this. Any error logs?

**Comment by cycloidsoftware** [comment]
This seems to work as intended now after reinstalling SourceMod.  I was doing some maintenance earlier, so I cannot say that the re-install was the fix, but it's likely something went wrong on my end.
