### ISSUE TITLE
.Throw doesnt work anymore

### ISSUE THREAD

**Issue by cyrill100** [splewis/csgo-practice-mode#76]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
.throw should throw the Nade categories

### Actual behavior
.throw says it throws the Nades but nothing happens

### Steps to reproduce
- Plugin version: 1.2.2
- csutils version: 1.2.2
- Sourcemod version: 1.8.0.6041

**Comment by JackJack3231** [comment]
This has already been fixed in newer developement Versions.
If you need .throw try one of the development versions e.g.
https://ci.splewis.net/job/csgo-practice-mode/203/

**Comment by cyrill100** [comment]
Thanks for your fast reply.
It worked.
