### ISSUE TITLE
bot takes forever to spawn after kill (via .bot)

### ISSUE THREAD

**Issue by dawidx0** [splewis/csgo-practice-mode#77]
### Expected behavior:
bot to spawn couple of seconds after killing it. (bot spawned via .bot)

### Actual behavior:
bot takes many seconds to spawn

### Steps to reproduce:
simply enable .setup (practicemode) spawn a bot (.bot) and kill it. it takes forever to spawn

- Plugin version: 1.2.2
- Sourcemod version: 6041

**Comment by splewis** [comment]
Already fixed for the next version: https://github.com/splewis/csgo-practice-mode/issues/65
