### ISSUE TITLE
.noclip and infinite money currently requires Cheats enabled

### ISSUE THREAD

**Issue by SM411** [splewis/csgo-practice-mode#8]
It took some time for me to figure this out. Previous .noclip and infinite money worked independent on cheats enabled or not. With the newest versions this has changed. I think it might be a bug, but if intended, the infinite money and noclip settings in setup menu should be greyd out when cheats are disabled so users understand why their praticemode is not working.

**Comment by splewis** [comment]
You're right, that was an oversight. Fixed now: https://github.com/splewis/csgo-practice-mode/commit/4638c49bda2440514b1d22e71cfc31de728ab3f4
