### ISSUE TITLE
cant compile practicemode.sp

### ISSUE THREAD

**Issue by russh3l** [splewis/csgo-practice-mode#80]
Getting error when i try compile practicemode.sp -> http://prntscr.com/iu8x79

### Steps to reproduce
- Plugin version: 1.3.1
- Sourcemod version: Windows 6041

**Comment by splewis** [comment]
Use a newer version of the botmimic include: https://github.com/peace-maker/botmimic/blob/master/scripting/include/botmimic.inc

**Comment by russh3l** [comment]
thank you so much
