### ISSUE TITLE
BotMimic Issues 

### ISSUE THREAD

**Issue by KilljackTv** [splewis/csgo-practice-mode#82]
If reporting a bug, fill in the following sections:

### Expected behavior
This happends when right when i started up the server and used .setup in chat
### Actual behavior
[1] BotMimic_IsPlayerRecording
 [2] Line 60, ./scripting/practicemode/botreplay.sp:
   :Replays_OnThrowGrenade
  [3] Line 1472, ./scripting/practicemode.sp::CSU_OnThrowGrenade
  [5] Call_Finish
   [6] Line 311, ./scripting/csutils.sp::GetGrenadeParameters

### Steps to reproduce
Not much just add the new version of sourcemod and metamod and this issue comes up!
- Plugin version:
- Sourcemod version:
Source 1.80
Metamod 1.10.7

**Comment by splewis** [comment]
Can you run ``sm plugins list`` in the server console and paste the output?

**Comment by KilljackTv** [comment]
Sure can

**Comment by KilljackTv** [comment]
01 "Admin File Reader" (1.8.0.6041) by AlliedModders LLC
  02 "Admin Help" (1.8.0.6041) by AlliedModders LLC
  03 "Admin Menu" (1.8.0.6041) by AlliedModders LLC
  04 "Anti-Flood" (1.8.0.6041) by AlliedModders LLC
  05 "Basic Ban Commands" (1.8.0.6041) by AlliedModders LLC
  06 "Basic Chat" (1.8.0.6041) by AlliedModders LLC
  07 "Basic Comm Control" (1.8.0.6041) by AlliedModders LLC
  08 "Basic Commands" (1.8.0.6041) by AlliedModders LLC
  09 "Basic Info Triggers" (1.8.0.6041) by AlliedModders LLC
  10 "Basic Votes" (1.8.0.6041) by AlliedModders LLC
  11 "Client Preferences" (1.8.0.6041) by AlliedModders LLC
  12 "csutils" (1.3.1) by splewis/Deathknife
  13 "Fun Commands" (1.8.0.6041) by AlliedModders LLC
  14 "Fun Votes" (1.8.0.6041) by AlliedModders LLC
  15 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
  16 "Nextmap" (1.8.0.6041) by AlliedModders LLC
  17 "Player Commands" (1.8.0.6041) by AlliedModders LLC
  18 "CS:GO PracticeMode" (1.3.1) by splewis
  19 "Reserved Slots" (1.8.0.6041) by AlliedModders LLC
  20 "Sound Commands" (1.8.0.6041) by AlliedModders LLC
