### ISSUE TITLE
.map/sm_practicemap works outside of practice mode

### ISSUE THREAD

**Issue by cycloidsoftware** [splewis/csgo-practice-mode#83]
### Expected behavior
- .map/sm_practicemap only works when in practice mode

### Actual behavior
- .map/sm_practicemap can be used during 10mans (via pugsetup), etc.

### Steps to reproduce
- Plugin version: 1.3.1
- Sourcemod version: 1.8.0.6024

**Comment by splewis** [comment]
This is intended behavior, although there is a conflict between pugsetup/practicemode where both show menus on .map so one preempts the other. 

I'm open to changes where a cvar enables/disables one, though.

**Comment by cycloidsoftware** [comment]
I'll have to get myself started with SourcePawn before I make a fork.  I'll look into implementing this.

**Comment by splewis** [comment]
I'm closing this since I don't think it's an important enough change to keep a bug open for - I'm still willing to accept a PR for it, though.
