### ISSUE TITLE
Option to remove smoke, after it has deployed

### ISSUE THREAD

**Issue by fk73esport** [splewis/csgo-practice-mode#88]
Hi There

Im new here, so i dont know, if i am posting in the right place, sry if im not :-D

I was just wondering, if you could/ would add a option to remove a smoke nade after it has deployed, so you dont have to wait the 15 sec for it to go away?

Just a thought

Regards Ole

**Comment by PaulMur** [comment]
Hey @fk73esport 

Just wanting to find out have you used the script that is sent on that Reddit thread, it looks to be set up quite nicely so you can use the command alias. Maybe even set it up as a bind! 

If a lot of people find this useful, I'm sure the splewis would consider adding it as part of the config although not sure how the config from that Reddit post works yet, I must look into the config.

- Mars

**Comment by fk73esport** [comment]
forget about the Reddit post, just found out, it dossent worke, sry 4 the link post

**Comment by PaulMur** [comment]
Haha!

I had a feeling it wouldn't work as it would mean having to remove the model and I'm not sure that's possible in this sense. 

Don't forget to close the issue 😄 

Have a good one 

- Mars
