### ISSUE TITLE
Is it possible to load a different grenade .cfg?

### ISSUE THREAD

**Issue by Joele25** [splewis/csgo-practice-mode#97]
I have two team practicing on the same server but I dont want that one of them can see the smoke of the other, can I execute a different granade .cfg in some way?

**Comment by splewis** [comment]
No, it's not possible right now.

**Comment by splewis** [comment]
I also don't intend on adding this - so I'm going to close it. If someone ones to a submit a pull request to merge it, I'd probably be okay with it as long as it handled backups appropriately.
