### ISSUE TITLE
.help not working

### ISSUE THREAD

**Issue by OfficialSui** [splewis/csgo-practice-mode#99]
Hey,

i just setup the mod on my csgo server instance which is installed via the pufferpanel webpanel. The mod pretty much works just as intended, except .help which is just not doing anything. Any idea on how to fix this issue?

Thanks in advance.

**Comment by splewis** [comment]
Yes, .help doesn't work since the motd window was removed.

https://github.com/splewis/csgo-practice-mode/issues/96
